### PR TITLE
fix 39 : Add option to unlock screen before stating Tests

### PR DESCRIPTION
**Pull request by the-dagger**
Fixes issue #39
Changes : 
Add support for tests
@daminisatya Please merge this as this should fix the failing Travis tests.

### CODE REVIEW

**Comment by daminisatya** [comment]
@the-dagger so we still need the issue 39 right?

**Comment by the-dagger** [comment]
Yep, that is still required.

**Comment by daminisatya** [comment]
+1

**Comment by jig08** [comment]
@the-dagger This was much required, could you pls squash all your commits before we can merge this ?

**Comment by the-dagger** [comment]
Android studio messed commits up.
Closing this and sending another one.

**Comment by jig08** [comment]
Cool.

Follow up : PR #164

**Pull request closed without merging**
