### PR TITLE
Materialized the App. Addressed #10.

### PR DESCRIPTION
**Pull request by betterclever**
Solved issue #10. Attached are the screenshots of the new design. 
screenshot_20160926-090319
screenshot_20160926-090338

### CODE REVIEW

**Comment by daminisatya** [comment]
@betterclever Please provide a description. Link to the Issue. along with screenshots. It would be easy for reviewer to give code comments!

**Comment by betterclever** [comment]
I'll be sending a new PR with conflicts resolved.

**Comment by betterclever** [comment]
Final List of changes:

1. Materialized the app.
2. Displayed no internet connection snackbar in case of internet unavailability. #9 
3. Moved RecyclerView Adapter for chatView to correct package.

**Comment by shivenmian** [comment]
@the-dagger @betterclever Please do a squash when you are merging. Reverting this.

**Comment by shivenmian** [comment]
@betterclever Please squash your commits from next time, else PRs can't be merged.

@the-dagger Please don't merge un-squashed PRs from now. Thanks.

**Comment by the-dagger** [comment]
@shivenmian github allows commits to be squashed during merging. 
So I don't think that this should be an issue.

**Comment by shivenmian** [comment]
I know they do, I thought you didn't. Checked now, no problem @the-dagger

**Pull request merged**
