### PR TITLE
Refracting and improving code quality [Do not Merge]

### LINKED ISSUE #1188: Refactor code to improve code quality
**Actual Behaviour**
There are many typos in code, many indentation problems. A simple lint test will display these issues.

**Expected Behaviour**

Fix all these refracting issues and thus improve code quality.

**Would you like to work on the issue?**
yes

### PR DESCRIPTION
**Pull request by mamakancha**
Fixes #1188 

Changes: 
1. Refracting
2. Fixing Typos
3. Fixing Indentations
4. Removing extra imports and variables
5. Fixing lint issues
6. Improving overall code quality

### CODE REVIEW

**Comment by arundhati24** [comment]
@mamakancha Please open separate issues for separate changes, if they need to be addressed. That would help other contributors stay aligned with the changes made.
Also, please use informative commit messages so that the changes made become clear to anybody working on the project.

**Comment by mamakancha** [comment]
@arundhati24 This PR fixes single issue only which is to improve code quality. The code base is big, so I keep committing changes whenever I have changed significant code. And the commit messages does not make any sense cause I am gonna squash them into one as it solves only one issue.

**Comment by arundhati24** [comment]
@mamakancha imho it's not a good practice, because as you rightly mentioned the code base is big and improving code quality is more of a general thing. It doesn't give a clear idea in what terms you have been trying to improve the quality here. For e.g. you mentioned refactoring code. Code refactoring itself includes tonnes of things like collapsing hierarchy, decomposing conditionals and so on. If you simply say code refactoring that doesn't clarify what changes you have made to the code. And there's a high chance of introduction of regression when you refactor code. So, I still suggest you to break down this issue into simpler ones and send separate PRs for each so that there's not a lot of change in the code in a single PR and that would also help us maintain a better record of the changes made.
@chiragw15 @mariobehling what do you suggest?

**Comment by mamakancha** [comment]
> It doesn't give a clear idea in what terms you have been trying to improve the quality here.

Firstly, this PR clearly states in the heading "DO NOT MERGE" which means that this is not complete. So, you won't get a clear idea right now about what I am trying to do. Let me complete it first, I will then update the PR to mention what all I have done in this PR and on what terms I have been trying to improve the quality here.

> you mentioned refactoring code.  Code refactoring itself includes tonnes of things like collapsing hierarchy, decomposing conditionals and so on.

Again, this PR is not complete. So, I haven't mentioned what all I am refracting. I will clearly mention each and everything I have done in this PR but after I have completed the work. 

> So, I still suggest you to break down this issue into simpler ones and send separate PRs for each so that there's not a lot of change in the code in a single PR and that would also help us maintain a better record of the changes made.

No. This is a SINGLE issue and can not be broken down further. For instance, I fixed typos, fixed indentation issues and removed useless empty lines. So, it does not make any sense to open a new PR to fix indentation and fix typos separately. Only one PR with the heading "Improve code quality" is sufficient imho. 

Rest @chiragw15 can tell.

**Comment by arundhati24** [comment]
@mamakancha Yes. Please ask @chiragw15 :smile: 
I agree that typos and minor changes like indentation can be done in one PR but I still feel code refactoring and fixing lint issues should be kept separate.
Rest, as the project maintainers might suggest, please go ahead with that. That was just my opinion because code refactoring is itself a big task.

**Comment by iamareebjamal** [comment]
@mamakancha Please finalize this. Though ideally, one PR should handle one issue only. This is needed so that codebase can be improved. Please, either fix this or someone else should take this up

**Comment by mamakancha** [comment]
Yep. Take it up.

**Comment by iamareebjamal** [comment]
I'm closing this. @arundhati24 Please send a new PR

**Pull request closed without merging**
