### PR TITLE
Fixes #537 Search text chage sensitive.

### LINKED ISSUE #537: Make search text change sensitive.
**Actual Behaviour**

If the user wants to search something he has to type the thing and press search.

**Expected Behaviour**

In most apps like WhatsApp and messenger the search results gets updated as the user types text. We should implement a similar feature in our app.

Should I send a PR for this?

### PR DESCRIPTION
**Pull request by free4murad**
Fixes issue #537 

Changes: The search is now text change sensitive.

### CODE REVIEW

**Comment by free4murad** [comment]
@Abhi2424shek 
Can you please help me with this.
Why is the test failing?

**Comment by Abhi2424shek** [comment]
Tests are passing

**Comment by free4murad** [comment]
@Abhi2424shek 
Yes i figured what the problem was.

**Comment by Abhi2424shek** [comment]
Ok 👍

**Pull request merged**
