### PR TITLE
refactor: welcome screen to handle orientation changes.

### PR DESCRIPTION
**Pull request by knight-shade**
Fixes: #1090

Changes:  WelcomeActivity is refactored to handle orientation change properly, previously during orientation change in middle of welcome screen, it automatically closes and goes to Login screen .

Screenshots for the change: 
whatsapp image 2018-01-07 at 10 11 31 am 3
whatsapp image 2018-01-07 at 10 11 31 am 2
whatsapp image 2018-01-07 at 10 11 31 am 1
whatsapp image 2018-01-07 at 10 11 31 am

### CODE REVIEW

**Comment by chiragw15** [comment]
@knight-shade Please see why Circle Ci test is failing.

**Comment by knight-shade** [comment]
@chiragw15 I checked out why the tests are failing right after they failed, it is due to some bug in IDE AFAIK, no bugs in the code.

**Comment by chiragw15** [comment]
Okay. I have started the rebuild. If the build still does not pass, that means there is some problem with the code.

**Comment by chiragw15** [comment]
@knight-shade Build failing due to 
```
/home/ubuntu/susi_android/app/src/androidTest/java/org/fossasia/susi/ai/login/WelcomeActivityTest.kt: (52, 28): Unresolved reference: pager
e: /home/ubuntu/susi_android/app/src/androidTest/java/org/fossasia/susi/ai/login/WelcomeActivityTest.kt: (55, 28): Unresolved reference: tabDots
```
Please check.

**Comment by iamareebjamal** [comment]
@batbrain7 Please go ahead on issues with inactivity of more than one week. We can safely assume claim on such issues where author has not shown any indication of continuing the work

**Pull request closed without merging**
