### PR TITLE
Search query and messaging mismatch  issue #143 solved

### PR DESCRIPTION
**Pull request by piyush6348**

### CODE REVIEW

**Comment by jig08** [comment]
@piyush6348 
- Kindly give a description to your PR explaining the previous state, changes you made and what was the outcome in brief.
- Follow the policy of one commit per PR/issue, so squash your commits.
- As mentioned in the README, pls follow the pattern `Fixes #<issue number> : <commit message>` for commit and PR names to keep up with the dev and maintenance flow of the proj.

**Comment by piyush6348** [comment]
previous - While searching for messages, if we don't close the search view and start messaging then search view was not getting closed automatically
now- as we switch to messaging while searching in chats, the searchView closes automatically

**Comment by jig08** [comment]
@piyush6348 Thanks for the description, also work on the remaining two points mentioned above as well. Cheers !

**Comment by the-dagger** [comment]
@piyush6348 Please close the existing PR if you aim to open a new one.

**Pull request closed without merging**
