### PR TITLE
fix: made button corners rounded and added thumbs up/down button

### LINKED ISSUE #992: making button corners rounded and adding thumbs up/down image in  susi skills activity
**Actual Behaviour**

The button try it has rectangular edges which is not recommended for a good ui, also there is no image for rating positive and negative.

**Expected Behaviour**

The buttons should be rounded and there should be an image on the left of positive and negative rating 

**Screenshots of the issue**

**Would you like to work on the issue?**

yes

### PR DESCRIPTION
**Pull request by Arshilgenius**
fixes #992 

Screenshots for the change:

### CODE REVIEW

**Comment by anandwana001** [comment]
@Arshilgenius I would like to contribute on same and thinking if we can have 5-star rating system like this 
extreme

**Comment by chiragw15** [comment]
@Arshilgenius Design clash with #1016 . @yashLadha @Arshilgenius @anandwana001 Can you guys collectively come up with a common design.

**Comment by chiragw15** [comment]
@anandwana001 For 5 star rating system, you'll have to work on server as well. Currently we have count of people who rated positively and negatively. Can you think of some good UI for this?

**Comment by S2606** [comment]
@chiragw15 We can create a custom rating bar in android..

**Comment by Arshilgenius** [comment]
@chiragw15  Can i leave the rating design and just add the rounded button in this PR?

**Comment by yashLadha** [comment]
The rating is mot limited to five @Arshilgenius . May be first your PR can be merged and them i will integrate that svg and my PR can be merged. Views @chiragw15

**Comment by yashLadha** [comment]
@anandwana001 for that change we also have to update the server as well for that.

**Comment by Arshilgenius** [comment]
@yashLadha : yes that will be awesome. 
@chiragw15 : views?

**Comment by anandwana001** [comment]
@chiragw15 we can do some calculation like taking the total of negative and positive rating and according to that showing on 5-stars and we can also show the total number of users on UI. 
We can also use emojis as they will represent that how many of users are happy with the result by susi app.

**Comment by yashLadha** [comment]
Some skills are unrated so is there a case for 0 star...and what emoji will it be

**Comment by anandwana001** [comment]
@yashLadha we can take simple smiley face and sad face and showing number at bottom to that.

**Comment by chiragw15** [comment]
>we can do some calculation like taking the total of negative and positive rating and according to that showing on 5-stars

Yes you can simply do `positive/(positive+negative) * 5` to show rating out of 5. But that's not the point. The 5 star rating system is used to give a feedback about how much you liked or disliked something where 5 means, you likes it a lot and so on. In our case, we use rating to detect whether response from server is correct or not. Suppose, you asked `hi` and the answer from server is `asd` which is not correct, therefore you would downvote it. So, we only need an upvote and downvote button for now. If you also show 5 star rating, it will confuse user because they would think it as a 5 star rating system but whereas actually it is a simple upvote and downvote case.

**Comment by yashLadha** [comment]
@chiragw15 what we can do is that we can use a grid of 2 cols .One for positive and other for negative

**Comment by yashLadha** [comment]
And show a progressive circuar bar, like a pie chart. With increasing color darkness

**Comment by Arshilgenius** [comment]
@chiragw15 please merge this.

**Pull request closed without merging**
