### PR TITLE
fix: Backbutton press in SkillsActivity

### LINKED ISSUE #995: Bug in handling back button press from About and Settings fragments
**Actual Behaviour**

When the back button is pressed from the About and Settings fragment **after being launched from SkillDetails fragment**, causes the title to change to "SUSI.AI Skills", with the same fragment being displayed.

**Expected Behaviour**

The back button should close the current fragment and show the previous fragment on the stack.

**Steps to reproduce it**

Open the skill details activity for some skill (eg, Cooking Guide). Now, open the About or settings page. On pressing back once, the title changes to "SUSI.AI Skills", without the fragment closing.

**Screenshots of the issue**

  

**Would you like to work on the issue?**

Yes, I would.

### PR DESCRIPTION
**Pull request by Muks14x**
Fixes #995 

Changes: 

AboutUsFragment and ChatSettingsFragment both inherited from android.support.v4.app.Fragment, whereas SkillDetailsFragment and SkillListingFragment use android.app.Fragment. This was causing problems with the fragment manager stack. So, for uniformity, changed everything to use the compatibility library.

Now, on pressing back, everything goes back to the skill listing fragment.

### CODE REVIEW

**Comment by Muks14x** [comment]
Yes, one would have to press back twice to go back, but opening up whatever was directly above in the hierarchy is what feels most natural to me in android. Instead of jumping back 2 screens, don't we generally expect the last screen we saw to be displayed, on going back? O.o

**Comment by collinx** [comment]
Imo, settings and about us fragments should direct the user to chat activity on back button pressing. what do you think @chiragw15 ?

**Comment by Muks14x** [comment]
It's not a huge change😄. I'll change it that way if needed. It's pretty easy to change it back too.

**Comment by chiragw15** [comment]
Since the about and settings fragment are opened from clicking on the item in the menu of Skill Activity, changing activity on pressing back should not be done imo. So, implement something like, when user is on Settings, About or Skill Detail fragment and he presses back button, open skill List fragment and when on skill List fragment open Chat Activity. What say @collinx @Muks14x

**Comment by collinx** [comment]
@chiragw15 fine by me 👍

**Comment by Muks14x** [comment]
@chiragw15 If I understand you correctly, I think that's how I've implemented it, can you check it out and see if you need changes?

**Pull request merged**
