### PR TITLE
Added Intro Screens

### LINKED ISSUE #894: Add intro screens
Add intro screens when an app is installed for the first time. They will include:
1. Displaying Skills.
2. Quick Info about Speech input/output.
3. Hotword and Hotword Training.
4. Login/Signup

### PR DESCRIPTION
**Pull request by Arshilgenius**
Fixes #894 Added Intro Screens

### CODE REVIEW

**Comment by Arshilgenius** [comment]
@chiragw15  I've resolved the issue, Please check now

**Comment by Arshilgenius** [comment]
@chiragw15 : Why is no one responding?

**Comment by chiragw15** [comment]
@Arshilgenius can you please check what is wrong with circle ci.

**Comment by Arshilgenius** [comment]
screen shot 2017-09-08 at 8 15 27 pm

@chiragw15 
Maybe Because of this?

**Comment by Arshilgenius** [comment]
@chiragw15  Please Merge.

**Comment by mariobehling** [comment]
Ok, so let's test this.

**Pull request merged**
