### PR TITLE
fix: Language matched with country

### LINKED ISSUE #1939: Rename strings files names to match country
**Rename the strings files to match country**

To rename the strings files names as to match the country accordingly

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by immadisairaj**
Fixes #1939

Changes: Renamed the files to match language with respective countries

Screenshots:
https://user-images.githubusercontent.com/40348358/52577367-f6390b00-2e47-11e9-8f49-01225183994b.png

### CODE REVIEW

**Comment by arundhati24** [comment]
@immadisairaj Why do we need to do this?

**Comment by immadisairaj** [comment]
> @immadisairaj Why do we need to do this?

Because everything has to follow a certain way and here few files are in one format and rest in other format.
https://github.com/fossasia/susi_android/tree/development/app/src/main/res

**Comment by arundhati24** [comment]
Okay! So, there have been some new additions that follow a different naming.

**Comment by immadisairaj** [comment]
So, which naming style is recommended

**Pull request closed without merging**
