### PR TITLE
Fixes #15 :Solve soft keyboard get open automatically

### LINKED ISSUE #15: Soft keyboard get open automatically
After opening app soft keyboard get open automatically

### PR DESCRIPTION
**Pull request by amitiwary999**
Fixes issue #15 :Added some code in onPause method in mainactivity and also made some changes in activity_main.xml so that it solve soft keyboard get open automatically issue.

### CODE REVIEW

**Comment by the-dagger** [comment]
@amitiwary999 It seems like you again committed files which are not needed (gradle.xml and others)
I'd suggest you to carefully commit only that file which was changed by you before each commit.

**Comment by amitiwary999** [comment]
Yes I seen and trying to solve it.

**Comment by the-dagger** [comment]
Awesome :+1:

**Comment by amitiwary999** [comment]
I sent a new pull request(with only required file).

**Pull request closed without merging**
