### PR TITLE
Fixes #471 Fixed typing dots

### LINKED ISSUE #471: Dots are showing before the message is sent.
**Actual Behaviour**
the dots are showing before the message is sent.
screenshot_20170115-004410

**Expected Behaviour**
The dots should shown after the message is delivered. As in any other IM apps. say ALLO.
and dots should get hide after reply.

**Steps to reproduce it**
@the-dagger is this a valid issue?

**Would you like to work on the issue?**
If its really an issue.

### PR DESCRIPTION
**Pull request by shubhamvashisht**
Fixes  #471 
Changes: Now the typing dots will be shown only after users message gets delivered to the server and hides after reply is set to the recyclerview.
however, dots are noticeable only if server takes some time give response back just like Allo.

### CODE REVIEW

**Comment by shubhamvashisht** [comment]
if an error occurs in susi_server, the response body will be empty?

**Comment by Abhi2424shek** [comment]
The errors are shown like network no found so can you do that too, the dots ideally mean it's typing something {thinking}

**Comment by daminisatya** [comment]
@shubhamvashisht Can you check the CircleCI fails?

**Comment by shubhamvashisht** [comment]
@Abhi2424shek only error i have seen yet is "internet connectivity problem!" and it is occuring very often.
need to find if its because of server false response.

**Comment by shubhamvashisht** [comment]
@daminisatya 
everything is fine. it says no view found matching (org.fossasia.susi.ai:id/down_angle), but its there.
how to build it again circleci?
gradleerrpr

**Comment by shubhamvashisht** [comment]
@daminisatya mam, can you please try to build it again, Build on my local machine is not giving any such error.

**Comment by Abhi2424shek** [comment]
It's passed so no worries.

**Comment by jig08** [comment]
@shubhamvashisht Squash your commits into one and we are ready to go.

**Pull request merged**
