### PR TITLE
Fixes #16 : Copy and Delete feature added.

### LINKED ISSUE #16: Copy, Delete, Forward, share option
After selecting the Text Copy, Delete, Forward, share option should pop up in the status bar.

### PR DESCRIPTION
**Pull request by mayank408**

### CODE REVIEW

**Comment by daminisatya** [comment]
@mayank408 I would love to see the color change. Can you add the screenshots?

**Comment by jig08** [comment]
@mayank408 Was the previous PR related to this issue closed ?

**Comment by mayank408** [comment]
@daminisatya Are u referring to color of time stamp.


whatsapp image 2016-10-12 at 3 51 56 pm

**Comment by daminisatya** [comment]
yes @mayank408 looks good. I remember seeing yellow last time.

**Comment by mayank408** [comment]
@jig08 issues resolved
1. color of time stamp changed.
2. snackbar is added instead of toast

I am just facing the problem in lifting the UI when snackbar is opened . I tried a lot but sry I could not implement it. So I am leaving it for some other.

**Comment by daminisatya** [comment]
Please open an issue for the same and refer it over here

**Comment by mayank408** [comment]
@jig08 I dont think there is any previous pr related to this issue.

**Comment by mayank408** [comment]
@the-dagger Travis test failing again even after all necessary changes..

**Comment by betterclever** [comment]
@mayank408 Deletions are temporary in your code. On reopening app , messages reappear. Delete messages from database too.

**Comment by mayank408** [comment]
@betterclever I was said to do so thats why i did . I asked for this as well.

**Comment by the-dagger** [comment]
@mayank408, @betterclever Is right, on deleting the messages, they should be deleted from the database too.
Where is the discussion in which you were instructed not to do so?

**Comment by mayank408** [comment]
@the-dagger Sorry there was some confusion between @nikhilbalyan @amitiwary999 and me .

**Comment by the-dagger** [comment]
@mayank408 Please send another PR which addresses this issue.
I will reopen #16

**Pull request merged**
