### PR TITLE
fix: unclickable mic or send icon in chat activity

### LINKED ISSUE #2094: Mic icon in chat fragment becomes un clickable after using susi voice recogniser for one time.
**Describe the bug**
The microphone image present in chat activity fails to prompt the voice recogniser fragment when clicked, if it has been used once. This shows that voice command can be accepted by susi only one time, when the app is running. 

**Expected Behaviour**
User should be able to use voice command as many time he/she wants.

**Steps to reproduce it**
Go through the code.

**Screenshots of the issue**
dwer

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | Redmi Note 5 Pro|
|Android Version|  Oreo 8.1    |

**Would you like to work on the issue?**
Yes

### LINKED ISSUE #2207: Send Icon and Enter button becomes un clickable once we use susi voice
**Describe the bug**
The send icon and the enter button stops working if we use susi voice for once. It becomes unclickable and doesn't allow to send any message or voice message. 

**Expected Behaviour**
The icon should be clickable to send next messages, even after we use voice search.
 
**Steps to reproduce it**
Open ChatActivity, click on the microphone. Give some voice instruction. After getting reply, try to send any other query via voice or text. It won't work.

**Similar Issue**
#2094 

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | RedMi Note 5 Pro |
|Android Version| Oreo 8.1    |

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by atm1504**
Fixes #2207 
Fixes #2094 

Changes: 
Changed the way of opening the chat activity from stt fragment. The mic or the send icon is now clickable in all cases.

Screenshots for the change: 
ezgif com-video-to-gif

### CODE REVIEW

**Comment by atm1504** [comment]
Further work on it can be done only after #2244 is solved.

**Comment by atm1504** [comment]
@iamareebjamal I have found a better solution and simple which don't require restarting. Just, we need to enable the icon button, which was getting disabled. Also, I will fix the minor UI issue related to it. So, I am closing this pr, as it has many irrelevant changes and opening a new pr.

**Comment by liveHarshit** [comment]
> I am closing this pr, as it has many irrelevant changes and opening a new pr.

Bad habit. Learn Git well, it won't be a problem.

**Comment by atm1504** [comment]
@iamareebjamal please review it now. Commit no 3c91fa8 is the final solution. Everything else has been reverted.

**Comment by atm1504** [comment]
@iamareebjamal please review it.

**Pull request merged**
