### PR TITLE
Fixes #360 : Issue regarding websearch

### LINKED ISSUE #360: Show a google search result list for new answer action type "websearch"
**Actual Behaviour**

currently there is a hard-coded rule inside the app which triggers a web search.

**Expected Behaviour**

The app shall not decide on itself to perform a web search. It must only react on the actions as given in the actions object. To perform a web search, the actions object may now contain an action with the type "websearch". In case that such an action appears, use the value "query" inside the action object to get the actual query term for the web search.

The new actions array will probably contain two actions, one with an normal answer type and another with the new websearch type. Both actions must be performed in the same order as given in the actions array

**Steps to reproduce it**

ask susi the following string: "search for linux distibutions", or open http://api.asksusi.com/susi/chat.json?timezoneOffset=-60&q=search+for+linux+distributions. You will get an result json with the following actions array:
```
"actions": [
      {
        "type": "answer",
        "expression": "Here is a web search result:"
      },
      {
        "type": "websearch",
        "query": "linux distributions"
      }
    ]
```
Use the query object to query the google search result, in this case "linux distributions".
The app shall then show two things:
- the line "Here is a web search result:" - as taken from the expression object
- the google search result in the same window

### PR DESCRIPTION
**Pull request by mayank408**
Fixes issue #360

Screenshots for the change: 

whatsapp image 2016-12-12 at 4 07 16 pm

whatsapp image 2016-12-08 at 8 09 49 pm

### CODE REVIEW

**Comment by mayank408** [comment]
@the-dagger Have a look pls..

**Comment by mayank408** [comment]
@the-dagger Circle CI test failing again.

**Comment by mayank408** [comment]
@the-dagger ^^

**Comment by mayank408** [comment]
@the-dagger Resolved all the conflicts , now kindly merge this.

**Comment by HimanshuS01** [comment]
Hey @mayank408 .I was talking about this.Web Search Result is not displaying.Help me to figure out the problem.Thanks
2bf19a4c-9e40-46f2-a7cd-d1ddb1cb1103

**Comment by mayank408** [comment]
@HimanshuS01 Its not an issue , the web search take place only when the action is websearch , in this query the action is not websearch and the susi has the answer , so the answer is displayed . Thanks:)

**Comment by HimanshuS01** [comment]
Thanks @mayank408 for helping me :) . But what kind of searches  will result into an action "websearch". Is there  any specific keyword to  write  query?

**Comment by mayank408** [comment]
@HimanshuS01 No there is no specific keyword  , just if susi does not know the answer it will result in web search and as server kept updating so new answers also gets added.

**Comment by HimanshuS01** [comment]
@mayank408  So I and you  are  getting different results for same query.i.e modi. So was it bcoz of server getting updated?

**Comment by mayank408** [comment]
@HimanshuS01 Yup exactly I took these screenshots quite a few days ago , since then there must be update in the server. :)

**Pull request merged**
