### PR TITLE
Fixes issue #278 Implementation of 'Hi susi' as hotword wake up command

### PR DESCRIPTION
**Pull request by anantprsd5**
Fixes issue #278 

Changes: Added "Hi Susi" as hotword wake up command which will trigger the Google speech input on hotword detection

### CODE REVIEW

**Comment by mayank408** [comment]
@anantprsd5 Could you provide me with the running apk...

**Comment by anantprsd5** [comment]
@mayank408 [link to apk](https://github.com/anantprsd5/Susi-Apk/blob/master/app-debug.apk)

**Comment by mayank408** [comment]
@anantprsd5 Is there any setting which I have to do because I m saying "Hi Susi" but its not reacting .

**Comment by anantprsd5** [comment]
@mayank408 Please check whether write storage and record audio permissions are set. If it's set then it should work, it might not be accurate enough.

**Comment by mayank408** [comment]
@anantprsd5 What should I suppose to use as a hot word?? Or there is only a single hotword.

**Comment by anantprsd5** [comment]
@mayank408 "hi susi" is the only hotword. Is it not working with you?

**Comment by mayank408** [comment]
@anantprsd5 No its not working for me..

**Comment by anantprsd5** [comment]
@mayank408 Thank you for testing. I will have to check with another device then to sort the issue, as for me it's working. Will let you know.

**Pull request closed without merging**
