### PR TITLE
Fix : reduce complexity of ChatFeedRecyclerAdapter[Work in progress]

### PR DESCRIPTION
**Pull request by amitiwary999**
Fixes issue #654

### CODE REVIEW

**Comment by chiragw15** [comment]
@amitiwary999 Is the work completed in this pr?

**Comment by amitiwary999** [comment]
I have moved required code but there is a problem in removing clicklistener. I have tried to move clicklistener but facing some problem. I will try to fix it.

**Comment by amitiwary999** [comment]
@chiragw15 I think now we don't need longclicklistener for map,rss and websearch part. Now it will be easier to move to respective viewholder.

**Comment by chiragw15** [comment]
Okay, go ahead then. If you need help, message me.

**Comment by amitiwary999** [comment]
opened new pr  [here](https://github.com/fossasia/susi_android/pull/763). This pr has very large merge conflict

**Pull request closed without merging**
