### PR TITLE
Fixes #510 : reduce the build time

### LINKED ISSUE #510: reduce the build time
**Actual Behaviour**

build time on my machine is 1 mins 11secs

**Expected Behaviour**

after modifying the gradle files, build time reduced to 23 secs and 458 msecs

**Steps to reproduce it**

modifying the gradle.properties reduced the build time. 

**Would you like to work on the issue?**

yes

### PR DESCRIPTION
**Pull request by DravitLochan**
Fixes issue #510 
Changes: enhanced the gradle properties

### CODE REVIEW

**Comment by DravitLochan** [comment]
Updates: earlier, the first build time was 2 mins 11 sec. Now, the first build time is 53secs 911 msecs.

**Comment by DravitLochan** [comment]
haha. i know. but I was going by the flow and hence made this. I have created another issue which again is an outcome of the flow.  (:

**Comment by jig08** [comment]
@DravitLochan Pls go through the [Coding Practices](https://github.com/fossasia/susi_android#code-practices) as well.

**Comment by DravitLochan** [comment]
sorry for not realizing the ethics thing. won't violate them in future.

**Comment by DravitLochan** [comment]
is it done now?

**Pull request merged**
