### PR TITLE
feat: Move from Privacy fragment to signup activity

### LINKED ISSUE #2086: Allow user to move from Privacy Fragment to Sign Up Activity
**Describe the feature you'd like**
Users must be allowed to move directly from Privacy fragment to the SignUp Activity. ALso add "I accept terms and conditions in Privacy page."

**Additional context**
There are many users who would prefer to read the terms and conditions before signing up. Currently, we don't have any system which allows the user to move directly to the signup page from privacy fragment. So, at the bottom of the privacy fragment we should have an option that will allow the user to accept the terms and condition after going through it. The acceptance value should be stored in a preference. Just by accepting it, it should open the SignUp Activity. User can accept only if he is not logged in.

**Screenshots**
WhatsApp Image 2019-03-27 at 2 09 44 AM

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by atm1504**
Fixes #2086 #2111 

Changes: 
* User now can accept terms and policy in privacy fragment page. Clicking on this will redirect to the signup page.
* If user is logged in, then privacy page shows that he has accepted the terms and conditions.
* Handled all possible cases that would have happened with user login. 
* Properly implemented the main concept of accepting terms and conditions.

Screenshots for the change: 
privacy

### CODE REVIEW

**Comment by atm1504** [comment]
@iamareebjamal @batbrain7 @arundhati24 please review it

**Comment by atm1504** [comment]
@iamareebjamal please review it. I have implemented this method efficiently.

**Comment by atm1504** [comment]
@iamareebjamal @batbrain7 @arundhati24 please review it.

**Comment by arundhati24** [comment]
@atm1504 If I understand correctly, you are taking the user to the privacy page if the checkbox is unchecked. Wouldn't it be good if we link the "Terms and Conditions" to the privacy page rather than opening the page ourselves? So, what I mean is if a user wants to read it, she/he will click on "Terms and Conditions" and read and then accept the terms from there or return and check the box on the signup page. Or if the user simply wishes to check the box and continue without actually opening the privacy page for whatever reason, then she/he can choose to do that.

**Comment by Bhavnaharitsa** [comment]
@arundhati24 yes! Probably the terms and conditions when the user clicks we could may be ask if he wants to visit. Because most of the times the users dont prefer to read the privacy page and straight away click accept. There could be an alert box asking if he wants to visit the privacy page else he could simply accept the terms and conditions and enjoy the service of the app.

**Comment by atm1504** [comment]
@arundhati24 in few apps, I found the style that I implemented here. I can change it if you want. But I preferred it a better way. Because in few Google apps/webpages we are asked to read the entire privacy conditions before accepting it.

**Comment by atm1504** [comment]
@arundhati24 please provide your views

**Comment by atm1504** [comment]
@iamareebjamal please review it.

**Comment by atm1504** [comment]
@arundhati24 @iamareebjamal @batbrain7  please review it. Because this pr has resolved a few minor problems related to susi menu display and its state to redirect to the login page.

**Comment by mariobehling** [comment]
Low priority and we need to think it through. Maybe out of scope for now.

**Pull request closed without merging**
