### PR TITLE
Fixes #427 : Google search feature added

### LINKED ISSUE #427: No Search Results Found
**Actual Behaviour**

Whenever it answers 'I dont know how to answer this.Here is the web search result:' No search results are found.

**Expected Behaviour**

It should produce the results from Google search.

**Screenshots of the issue**

screenshot_2016-12-21-12-17-47

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by mayank408**
Fixes issue #427 

Changes: Google search feature added.

Screenshots for the change: 

screenshot_1482501362

screenshot_1482501355

### CODE REVIEW

**Comment by mayank408** [comment]
@the-dagger @daminisatya @jig08 Hey have a look at this , I have implemented google chrome custom tabs to show the search result , its fast and optimisable .

**Comment by jig08** [comment]
@mayank408 Looks nice.
* Rename your commit accordingly as `Fixes #issue-number: <commit message>`.
* Fix build errors pls.
Cheers !

**Comment by mayank408** [comment]
@the-dagger Circle ci failing again , have a look pls....

**Comment by mayank408** [comment]
@jig08 @the-dagger Is there any changes required....

**Comment by mayank408** [comment]
@daminisatya. Sorry , I didn't get you . What changes you required...?

**Comment by the-dagger** [comment]
I believe they are not squashed and don't follow the guidelines.

**Comment by the-dagger** [comment]
@mayank408 I'll have a look at the failing CircleCi tests after 30th, have exams till then.

**Comment by mayank408** [comment]
@the-dagger ok got it , thanks :)

**Comment by samsruti** [comment]
@mayank408 Please change the commit name to
Fixes #issue-number: <commit message>.

**Comment by mayank408** [comment]
@daminisatya Changes done..

**Comment by mayank408** [comment]
@samsruti @daminisatya done.

**Comment by samsruti** [comment]
@mayank408  Thanks 👍

**Pull request merged**
