### PR TITLE
Fixes #186 Waitingdots feature added

### LINKED ISSUE #186: Need of Writing Hint
1.There should be a writing hint while Susi is typing something as it feels unrealistic when someone ask any ques and with no time Susi replies back.It is inappropiate and Susi will give a feel that there is other person typing..In response to time taken by us to write something,same time should be shown of Susi.

### PR DESCRIPTION
**Pull request by mejariamol**
Fixes issue #186 
Changes: Waiting dots feature added

Screenshots for the change:

### CODE REVIEW

**Comment by daminisatya** [comment]
Woah, Interesting one. Thank you! Is there an issue for this?

**Comment by jig08** [comment]
@daminisatya Issue https://github.com/fossasia/susi_android/issues/186

**Comment by mejariamol** [comment]
@daminisatya  yeah. issue #186

**Comment by jig08** [comment]
@mejariamol Pls resolve Codacy issues before we can merge this.

**Comment by the-dagger** [comment]
@mejariamol There was a merge conflict, could you resolve it?
Please make sure to follow the discussion on #243 before resolving the conflicts.

**Comment by mejariamol** [comment]
Due to network problem couldn't commit completely. will try later

**Comment by mejariamol** [comment]
I am helpless now :)
couldn't understand what is merge remote-tracking... . I think I have committed all required changes.

**Comment by mejariamol** [comment]
@the-dagger, @daminisatya and @jig08  now I think its good to get merge. :-p
finally all checks have passed. :)

**Comment by daminisatya** [comment]
@mejariamol  Resolve the conflicts. and also we have a system for creating a pull request, which helps us maintain the code well. Please have look over here

https://github.com/fossasia/susi_android#code-practices

**Comment by mejariamol** [comment]
@daminisatya what is conflict here? I didn't get it. why the `ChatFeedRecyclerAdapter.java` is appearing as conflicting file.

**Comment by mejariamol** [comment]
@daminisatya, @the-dagger  and @jig08 plz tell me how to rename folders. Conflict is due to the folder names mismatch with package names.
since i changed package names to lowercase i.e. `package org.fossasia.susi.ai.adapters.recycleradapters` and `package org.fossasia.susi.ai.adapters.viewholders`

**Comment by the-dagger** [comment]
@mejariamol I'd suggest you to resync your fork and then send a new Pull Request.
There are way too many commits messed up here.

**Comment by mejariamol** [comment]
Ok I will do that. close this PR.
But we will have to rename folders names to lowercase to avoid conflict issue.
`app/src/main/java/org/fossasia/susi/ai/adapters/recyclerAdapters/`
`app/src/main/java/org/fossasia/susi/ai/adapters/viewHolders/`
these must be--
`app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/`
`app/src/main/java/org/fossasia/susi/ai/adapters/viewholders/`

**Comment by jig08** [comment]
>close this PR.

@mejariamol Closing it, make one afresh.

**Pull request closed without merging**
