### PR TITLE
Fix: Share icon on share button appears black 

### LINKED ISSUE #1672: Color of the share icon on share button appears black
**Actual Behaviour**

The color of the share icon appears black.

**Expected Behaviour**

The icon should be white in color.

**Device Used**

Le X526 - Android 6.0.1 (API level 23)

**Screenshots of the issue**

img_20180819_122642_749

img_20180819_122647_252

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by muarachmann**
Fixes #1672 

Changes: changed the fillcolor of the share icon from dark gray to white.  Found in the **app/src/main/res/drawable/ic_share_white_24dp.xml**

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Please follow commit guidelines

**Comment by muarachmann** [comment]
I did! .just that I commented on the issue and couldn't show a screenshot.
Please checkout my comment on the original issue. Nevertheless I will do
stick to instruction thanks for the notice

**Comment by iamareebjamal** [comment]
The commit title `Changed share button fillcolor to white` is not following the guidelines

**Comment by muarachmann** [comment]
Oh I see once on PC I will remedy that

**Pull request merged**
