### PR TITLE
Fixes #39 New Test cases added

### LINKED ISSUE #39: Addition of stricter unit tests.
Current unit tests on Travis just check for successful build but does not check whether various app functionality is working correctly or not.

We may add support for checking basic app functionalities like sending messages using androidTest framework so that errors like in #34  can be avoided.

### PR DESCRIPTION
**Pull request by abhi007tyagi**

### CODE REVIEW

**Comment by abhi007tyagi** [comment]
Can someone merge this PR?
No issues or conflict with code.

**Comment by mariobehling** [comment]
@abhi007tyagi Please check. Travis build is failing.

**Comment by abhi007tyagi** [comment]
@mariobehling  I think we should ignore these fails. Travis is giving similar errors for all test cases. The view is not visible to espresso for testing and it results as FAILED. The test cases are working fine on my device and emulator.

**Comment by gogeta95** [comment]
@abhi007tyagi Authentication test cases passed an hour ago. must something wrong with your tests. if it was travis issue auth tests would've failed too.

**Comment by abhi007tyagi** [comment]
@gogeta95  just checked your code. My cases are similar to yours. Also, I added 2 new test cases in this PR. If there is an issue in my code (for these 2 new cases), earlier test cases should have run to success. They too are failing!

From the logs, all I can get is the focus is not on the required view :(

**Comment by abhi007tyagi** [comment]
@gogeta95 now I can see the last two cases failing as your code has been merged. Now to run my cases, we need to be logged in.

**Pull request closed without merging**
