### PR TITLE
Fixes #495 Now we can open/launch other apps from susi

### LINKED ISSUE #495: Now we can open/launch other apps from susi
**Expected Behaviour**

Other apps can be launched from susi by command/message open+APP NAME
issue

**Would you like to work on the issue?**
Yes, done it.

### PR DESCRIPTION
**Pull request by shubhamvashisht**
Fixes #495 Now we can open/launch other apps from susi

Screenshots for the change: 
g_20170201_2250343

### CODE REVIEW

**Comment by shubhamvashisht** [comment]
@jig08 Please review this.

**Comment by the-dagger** [comment]
What happens if there are more than 1 app containing the input string of AppName?

**Comment by shubhamvashisht** [comment]
@the-dagger As a Hashmap cannot have duplicate keys, if two apps having same name are there then the latter one will replace first one. 
its very rare to have such conflict and even if there two apps with same name there functionality will be similar. for example if there are two camera apps with same label, any of that camera app will do the job.

**Comment by the-dagger** [comment]
Ok.
What if the user asks susi to open messenger?
There is a Google Messenger and a Facebook Messenger
Ideally a picker should open up asking which app to open

**Comment by shubhamvashisht** [comment]
Ok. will implement :)

**Comment by Abhi2424shek** [comment]
Yep but make it beautifull @shubhamvashisht

**Comment by jig08** [comment]
@shubhamvashisht Updates on this pls ?

**Comment by shubhamvashisht** [comment]
I will send pr today.

**Comment by Abhi2424shek** [comment]
@shubhamvashisht updates

**Comment by shubhamvashisht** [comment]
@Abhi2424shek i am on it. I got stuck into something.

**Comment by Abhi2424shek** [comment]
You are free to ask help @shubhamvashisht

**Comment by mayank408** [comment]
@shubhamvashisht It will not work if we query like "Can you please open Facebook" . Therefore before adding any new features we have to add natural language processing and every action will come from the server not from the app itself.
 @the-dagger @jig08 Can we close this for now...

**Comment by shubhamvashisht** [comment]
@mayank408  you are right.

**Pull request closed without merging**
