### PR TITLE
Enter as send working

### LINKED ISSUE #1476: Enter as Send - Not working on Google Board
**Actual Behaviour**

The enter as send is not working on Google Keyboard due to the suggestions they provide.

**Expected Behaviour**

It should work

**Steps to reproduce it**

Type a query and press enter

**Would you like to work on the issue?**

Yes

@arundhati24 Sending a PR

### PR DESCRIPTION
**Pull request by codedsun**
Fixes #1476 

Changes:Added to not show suggestions.
It has been working fine now on google keyboard too.

Screenshots for the change:

### CODE REVIEW

**Comment by codedsun** [comment]
@arundhati24 Now the fix will be working, as I had asus phone and they had ZENUI keyboard, so for google keyboard is also now made working

**Comment by arundhati24** [comment]
@codedsun So how to make sure that this works for all types of keyboards? Did you test it for different keyboards? e.g. swift keyboard.

**Comment by codedsun** [comment]
@arundhati24 After so many lookarounds, that's the best solution on the internet. The problem here is that keyboards have automatic suggestions on the keyword you type that hinders the "Enter key" to work properly. I can't guarantee you, as in the previous PR, it was working properly.

**Comment by arundhati24** [comment]
@codedsun Could you please add a GIF?

**Comment by arundhati24** [comment]
@codedsun What's the use of a feature that doesn't work for all types keyboards or devices? How can you say it is working then?

**Comment by arundhati24** [comment]
Also please make sure to remove the fields that you don't use. I can't see any screenshot. Did you miss adding it?

**Comment by codedsun** [comment]
@arundhati24 
>What's the use of a feature that doesn't work for all types keyboards or devices? How can you say it is working then?

The system used keyboard has settings to give suggestions which I think that "edittext" can't resolve
I can say it working as it's the only available solution for people around the internet and it also worked for my device too. 
Rest you all can check.

>Also please make sure to remove the fields that you don't use. I can't see any screenshot. Did you miss adding it?

Which fields are you referring to ? 
For screenshot yes I will add it

**Comment by arundhati24** [comment]
I request you to please look into it once again, because this is a very basic feature. I am sure there would be a way to implement it for all types of keyboards.

**Comment by codedsun** [comment]
@arundhati24 Now the PR Seems working for every keyboard and made that according to what's done in whatsapp :)

**Comment by codedsun** [comment]
@batbrain7 Check please

**Comment by codedsun** [comment]
@batbrain7 @arundhati24 Merge this!

**Comment by batbrain7** [comment]
let @arundhati24 approve first

**Comment by arundhati24** [comment]
@codedsun Would you please test it for other keyboards and then let us know? If it works, then we can merge this.

**Comment by codedsun** [comment]
@arundhati24 I have tested, if possible you all can also test after the merge 👍

**Pull request merged**
