### PR TITLE
fix: Changed status bar color

### LINKED ISSUE #2130: App top bar colour of few fragments are different from the theme
**Describe the bug**
The colour of the top bar of few fragments/ activities are different then the theme colour of the app. 

**Expected Behaviour**
All the activities and the fragment should have same colour at top, to maintain uniformity.

**Steps to reproduce it**
Change the colour of those fragments to colorPrimary.

**Screenshots of the issue**
Correct Display: 
signup

Incorrect bar colour:
settings1

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | Redmi Note 5 Pro |
|Android Version| Oreo 8.1    |

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by atm1504**
Fixes #2130 

Changes: 
* Changed the status bar colour in SkillsActivity

Screenshots for the change: 
After:

changed

Before:

settings1

### CODE REVIEW

**Comment by atm1504** [comment]
@batbrain7 I think it is not there in device activity. I will change that also and commit.

**Comment by iamareebjamal** [comment]
I don't think this should be changed. It looked better earlier

**Comment by atm1504** [comment]
@iamareebjamal sir in login page, signup, chat page we have primary dark blue colour as the status bar colour. I created this issue just to make the look uniform in all the activities of the app

**Comment by iamareebjamal** [comment]
I think Login/SignUp should also have dark gray status bar. The blue one is not consistent with Material Design but it is OK as it is

Please focus on features and bug fixes. There have been enough UI enhancements

**Comment by atm1504** [comment]
@iamareebjamal I have some plans on special features of Chat Activity can I start proceeding on those features. This features would make it more like a very useful assistant.

**Comment by immadisairaj** [comment]
@iamareebjamal @batbrain7 So, this PR can be closed as well as the issue related to this?

**Pull request closed without merging**
