### PR TITLE
Fixes #230: Add Copy, Delete and Share Options in Appbar.

### LINKED ISSUE #230: Add Copy, Delete and Share Options in the Appbar / ActionBar
**Actual Behaviour**

Currently, copy and delete option are available by long pressing the views. 

**Expected Behaviour**

It can be implemented in the ActionBar itself such that on long press on any message, its color changes and options are displayed there. It will also enable us to enable muliple deletion.

**Steps to reproduce it**

Not Required

*LogCat for the issue**

Not Applicable.

**Screenshots of the issue**

Not Required

**Would you like to work on the issue?**

Sure.

### PR DESCRIPTION
**Pull request by betterclever**
Fixes issue #230 

Changes:
1. Copy, Delete and Share Options added to Appbar. 
2. Multiple copy , delete and share also added.

Screenshots for the change: 

Already provided in the issue here, please refer #230

### CODE REVIEW

**Comment by betterclever** [comment]
Please don't merge it now. I'm fixing a small bug.

**Comment by jig08** [comment]
@betterclever Surely. Looks cool !

**Comment by betterclever** [comment]
@jig08  I have done changes to fix a little TTS bug. After this PR, following issues can be closed for sure. :smile: 
#199 #225 #230 #228 #243

**Comment by betterclever** [comment]
@jig08 Do I need to change something to get it merged?

**Pull request merged**
