### PR TITLE
Fixes #143 Search query and messaging mismatch

### LINKED ISSUE #143: Search query and messaging mismatch
While searching for messages, if we don't close the search view and start messaging then search view is
not closed automatically 
screenshot_2016-10-11-17-53-30-752_org fossasia susi ai

### PR DESCRIPTION
**Pull request by piyush6348**
Fixes issue #143 

Changes: added a condition in listener of editText of chat messages which checks for length of the search query which (if found >0) then the searchView is closed.

Screenshots for the change: [Add Screenshots or changes.]

### CODE REVIEW

**Comment by amitiwary999** [comment]
@piyush6348  are you working on this?

**Comment by piyush6348** [comment]
i've coded the issue but whenever I make a PR conflicts occur.

**Comment by amitiwary999** [comment]
@piyush6348 try to update your repo.

**Comment by jig08** [comment]
@piyush6348 Any updates on this please ?

**Comment by amitiwary999** [comment]
@jig08 I asked him if he want any help but he is not replying. I would like to work on this issue.

**Comment by piyush6348** [comment]
Sorry for replying lately @amitiwary999 , @jig08  i wasn't available lately.
@amitiwary999 i always make a new repo,make changes to it and then make a PR but it always gives me a merge error.

**Pull request closed without merging**
