### PR TITLE
chore: Release v1.2.0

### PR DESCRIPTION
**Pull request by atm1504**
Upgrading the app release version

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Please increment the version code and name

**Comment by atm1504** [comment]
> Please increment the version code and name

Please tell me how to give the release name.

**Comment by iamareebjamal** [comment]
One quality of a contributor is to first search, then try to find around what has been done before and then ask for directions after telling what you tried and where you failed. You just asked how to do it. Things like these are easier to do yourself if you have to tell someone how to do it

https://github.com/fossasia/susi_android/commit/f7c1b5126007add18dd42deb68fd17086ddaf8a8

**Comment by atm1504** [comment]
@iamareebjamal sorry. I will surely take care from now. Sorry, for my mistake.

**Pull request merged**
