### PR TITLE
Fixes #197: Log in Sign up UI updated.

### LINKED ISSUE #197: UI improvement for sign up and login screen.
### Would you like to work on the issue?
Yes

### PR DESCRIPTION
**Pull request by mayank408**
whatsapp image 2016-10-14 at 11 00 22 pm

### CODE REVIEW

**Comment by mariobehling** [comment]
Thank you. Please see my comments in the issue: https://github.com/fossasia/susi_android/issues/197#issuecomment-253961655

Please use light colors - white/grey for background of main area. Thank you.

**Comment by mayank408** [comment]
@mariobehling  ya sure 👍

**Comment by mayank408** [comment]
@the-dagger Pls have a look. Its showing there is no view such as down_angle.

**Comment by the-dagger** [comment]
Please sync your fork and send the Pull Request again so that it can pass CircleCI tests.

**Pull request closed without merging**
