### PR TITLE
fix: Correct code of existing user in signup page

### LINKED ISSUE #2051: "Existing user" option in Signup page malfunctions sometimes.
**Describe the bug**
"Existing user? Click here to login" opens ChatActivity some time.

**Expected Behaviour**
It should open LoginActivity instead.

**Steps to reproduce it**
Change the code. Write proper intent. Use Settings presenter's loginlogout function before passing the intent.

**Screenshots of the issue**
existing_user_defect

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | Redmi Note 5 Pro|
|Android Version| Oreo 8.1    |

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by atm1504**
Fixes #2051 

Changes: 
* Added the correct code in SignUpActivity.kt

Screenshots for the change: 
ezgif com-video-to-gif

### CODE REVIEW

**Comment by atm1504** [comment]
> Wrong implementation

Sir, can you please mention where I committed wrong in this code.

**Comment by iamareebjamal** [comment]
You don't create an activity and a presenter in another fragment to fix this issue

**Comment by atm1504** [comment]
> You don't create an activity and a presenter in another fragment to fix this issue

Sir for the intent to work correctly, I had to call the loginLogout function present in that settingPresenter class. So I had used that techniques. If this is wrong can you please suggest some other techniques.

**Comment by iamareebjamal** [comment]
Extract loginLogout in a separate component and use it

**Comment by atm1504** [comment]
@iamareebjamal please check wether this method id correct or not

**Comment by atm1504** [comment]
@iamareebjamal @batbrain7 @arundhati24  please review it.

**Pull request merged**
