### PR TITLE
Fixes #39 Added espresso test cases to check visibility of views

### LINKED ISSUE #39: Addition of stricter unit tests.
Current unit tests on Travis just check for successful build but does not check whether various app functionality is working correctly or not.

We may add support for checking basic app functionalities like sending messages using androidTest framework so that errors like in #34  can be avoided.

### PR DESCRIPTION
**Pull request by abhi007tyagi**
1. check main container views on app launch
2. check action bar item  on app launch

writing other test cases..

### CODE REVIEW

**Comment by abhi007tyagi** [comment]
@the-dagger Now this looks to be same as morning issue.. no travis related file updates from my end.
Can you do what you did in the morning?

**Comment by abhi007tyagi** [comment]
The test cases are working fine at my end. I have tested on emulator and Nexus 5 device. 
Please merge the PR.

One issue that I think would be, till the emulator is created and comes online, the waiting time for the test case to run gets over and hence giving us this error.

**Comment by the-dagger** [comment]
@abhi007tyagi Fixed.

**Comment by abhi007tyagi** [comment]
Please merge the branch !

**Comment by the-dagger** [comment]
@abhi007tyagi Can you push the pending tests too?

**Pull request merged**
