### PR TITLE
updated README.md

### PR DESCRIPTION
**Pull request by prakamya-mishra**
Changes:"The answers for user queries" instead of "The answers from user queries".

### CODE REVIEW

**Comment by prakamya-mishra** [comment]
I think the change was right but I don't why the test failed. can anyone tell the reason?

**Comment by chiragw15** [comment]
@prakamya-mishra Must be a glitch from Circle CI end. Restarted the build. Should pass, I guess.

**Comment by amitiwary999** [comment]
@prakamya-mishra thanks for your pr. Next time before sending any pr, you should open an issue and then send pr.

**Comment by prakamya-mishra** [comment]
Thank you @chiragw15 and @amitiwary999  for merging my PR. Next time I will keep in mind the to open an issue first. 
now what should I do to get FOSSASIA in my organisations list?

**Pull request merged**
