### PR TITLE
Fix : issue with date of retrieved old messages

### PR DESCRIPTION
**Pull request by amitiwary999**
Fixes issue #723 

Screenshots for the change: 
Before change
screenshot_2017-06-17-16-26-53

After Change
screenshot_2017-06-17-17-08-18

### CODE REVIEW

**Comment by amitiwary999** [comment]
@chiragw15 @mayank408  please review

**Comment by chiragw15** [comment]
Okay mistakes :
1. There are 2 date formats in app. Keep one. If you compare two same dates of different format using .equals() , they will be different.
2. No consideration of time zone. The date from server is an ISO 8601 date format with zulu time zone which is UTC 0. So basically you are showing dates.
3. Timestamp of retrieved message is timestamp at which it is retrieved and not at which it was queried.
4. Parsing of date in getdate() method is shitty.  
5. Answer Date should be displayed instead of query date.

**Comment by chiragw15** [comment]
Leave these points now. I have already implemented them while solving #712 . Don't implement them again and waste your and my time. Fix some other issue.

**Comment by amitiwary999** [comment]
It is not about current chat. This pr is related to retrieved old messages.

**Comment by chiragw15** [comment]
Already fixed in #728

**Pull request closed without merging**
