### PR TITLE
 Fixes #276 : Speech Output issue resolved.

### LINKED ISSUE #276: Enable Voice Output if user speaks to app
**Actual Behaviour**

Currently the user needs to enable voice output of Susi in the settings. Even if the user uses voice to communicate.

**Expected Behaviour**

* [x]  The output of voice should be enabled if users uses voice input.
* [x]  There should be an additional option in settings deactivate/activate Voice Output if user uses "Speech to Text", e.g. "At speech input enable speech out"
* [ ] The currently existing option "Speech Output" should be changed to "Speech Output Always On"

### PR DESCRIPTION
**Pull request by mayank408**
Fixes issue #276

Changes:Now the speech output is given only when the user gives input via speech to text.
It can be disabled in the settings as well.

Screenshots for the change: 
whatsapp image 2016-10-22 at 5 10 02 pm

### CODE REVIEW

**Comment by daminisatya** [comment]
@mayank408 What is the third option? not clear

**Comment by mayank408** [comment]
@daminisatya At speech input enable speech output.

**Comment by daminisatya** [comment]
We need to think of a simpler chat setting options. To a new person, i feel it's kinda of difficult.

**Comment by mayank408** [comment]
@daminisatya I will change it in my next pr for issue #284 . Please merge this for now. Thanks

**Comment by mariobehling** [comment]
Please read the issue description carefully. One point is missing.

**Comment by mayank408** [comment]
@mariobehling I did not get the meaning of 3 point . Could you explain what exactly I have to do.

**Comment by daminisatya** [comment]
@mayank408 If a reviewer's job is to just merge it, Then we would have suggested you to push code directly to master. The problem is not with the code merging and updating the existing issue in the next PR. We want the best to go in. Thank you

**Comment by mayank408** [comment]
@mariobehling Is it alright now?

whatsapp image 2016-10-22 at 8 11 19 pm

**Comment by mayank408** [comment]
@daminisatya Ok I will ensure the best possible practice.

**Comment by mariobehling** [comment]
Yes, good. Please set following as standard:

* Enter as send: Enabled
* Use mic for input: Enabled
* At speech input enable speech output: Enabled
* Speech output always on: Disabled

Of course use can change the setting.

**Comment by mayank408** [comment]
@mariobehling Standard values updated

**Comment by mayank408** [comment]
@mariobehling @daminisatya Is i have to make any changes to make it merged.

**Comment by mariobehling** [comment]
Thank you. Let's try this out a bit. Good progress.

**Pull request merged**
