### PR TITLE
feat: Alert dialog box on pressing skip in signup page

### LINKED ISSUE #2108: Prompt alert box in signup page if users press skip
**Describe the feature you'd like**
An alert box should be prompted if users press skip in signup page. The alertbox should ask the user if he/she confirms to skip the signup page.

**Additional context**
This feature is similar to the alert box that is already present in this page. Currently it appears only when back is pressed. It is the feature that is present in all professional apps.

**Screenshots**
alertbox

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by atm1504**
Fixes #2108 

Changes:
Created an alert dialog box.

Screenshots for the change: 
cgfgh

### CODE REVIEW

**Comment by iamareebjamal** [comment]
These are all minor enhancements. Please focus on bugs and features now

**Comment by atm1504** [comment]
Sir, I have found many major issues to work with. But working on those issues will take a long time as in some cases we need to change the code base a lot. I would love to work in those issues during the GSoC period, if I get selected.

**Comment by iamareebjamal** [comment]
UI refinements are not enough to get selected. You must prove that you are good enough to make big changes and move the project forward

**Comment by atm1504** [comment]
Sir, I will come up with some effective pr very soon.

**Pull request merged**
