### PR TITLE
Updated SDK and Support Library to latest.

### PR DESCRIPTION
**Pull request by betterclever**
Update Project SDK to version 24.0.2 and Support Library to 24.2.1
Added Latest Maven Gradle Plugin (1.4.1) for Android Studio 2.2.0 (Stable)
Included app module compile support when importing project in settings.gradle

### CODE REVIEW

**Comment by jig08** [comment]
@betterclever TravisCI check fails.
Kindly look into this.

```
$ rake
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
The command "rake" exited with 1.
```

**Comment by jig08** [comment]
Or push a customised `.travis.yml` first.

```
Could not find .travis.yml, using standard configuration.
```

**Comment by betterclever** [comment]
@jig08 As per the logs, the rake file is not found. I guess, this is a problem in travis CI container. rake file must be present there only. Correct me if I am wrong.

**Comment by mariobehling** [comment]
Are you gonna make a new PR?

**Comment by betterclever** [comment]
Yes. Squashing my changes, will be sending a PR soon.

**Pull request closed without merging**
