### PR TITLE
feat: Search skills in category fragments

### LINKED ISSUE #2208: Search Skill in All categories of skills page
**Describe the feature you'd like**
Currently, there is no way to search for the skill user is finding in all skill page. So, we should have a search feature on the page to search for a particular skill.

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by atm1504**
Fixes #2208 
Changes: 
The search process has been implemented

Screenshots for the change: 
ezgif com-video-to-gif

### CODE REVIEW

**Comment by liveHarshit** [comment]
The search bar is overlapping.

**Comment by atm1504** [comment]
> The search bar is overlapping.

Still now I am working in fixing the UI of the app. UI was not of great importance to us. We wanted to have this feature.

**Comment by liveHarshit** [comment]
> > The search bar is overlapping.
> 
> Still now I am working in fixing the UI of the app. UI was not of great importance to us. We wanted to have this feature.

Then add `wip` in the PR title.

**Comment by atm1504** [comment]
@iamareebjamal please review it now. I have fixed the minor issues.

**Comment by atm1504** [comment]
@iamareebjamal @batbrain7 @arundhati24 please review it.

**Pull request merged**
