### PR TITLE
fix: Show search results when searching in skills activity

### LINKED ISSUE #1800: Not show skill search result
**Actual Behaviour**

Toast "No skill found yet" appears, and nothing change

**Expected Behaviour**

The results of that have been entered appear

**Steps to reproduce it**

After the search button has been touched, then types the query, appears toast "No skill found yet"

**LogCat for the issue**

None

**Screenshots of the issue**

screenshot_susi ai_20181209-151830

**Would you like to work on the issue?**

Sorry, no

### PR DESCRIPTION
**Pull request by gaganag50**
Fixes #1800 and #1902 

Changes: 
The search icon remains hidden until all the skills are
retrieved and then shown when the retrieval is complete.
ListAdapter is used to display search results for proper
model diffing.

Screenshots for the change: 
### Search is not visible until all the network requests are fetched.
</img> 
## Search icon is visible and can perform searching when the requests are done.
</img>

### CODE REVIEW

**Comment by Bhavnaharitsa** [comment]
screenshot_20190306-082252_video player


I'm.afraid I'm not able to reproduce the error as the search shows even when it's loading

**Comment by gaganag50** [comment]
@Bhavnaharitsa, what is the situation when the search icon is showing? Search icon won't hide when the page is swiped for refresh because in this situation network request is not fired if the response are already there and hence the search icon should be working fine. On pressing the search icon list of all the available skills with non empty names should appear and search should work fine.

**Comment by gaganag50** [comment]
@iamareebjamal  please review my pull request

**Comment by iamareebjamal** [comment]
There are several unneeded changes. Please revert all of them

**Comment by gaganag50** [comment]
@iamareebjamal  I am not currently working on this. You can assign someone else to do this task.

**Comment by Bhavnaharitsa** [comment]
@gaganag50  Thanks! :D I would like to work on it .

**Comment by naman653** [comment]
@iamareebjamal I am trying to resolve this issue as it has been one of the major issues. My first approach was to update the skill results adapter with search results but somehow it is not updating. May I create a new fragment for search results.

**Comment by atm1504** [comment]
@batbrain7 @arundhati24 this issue has already been solved by @naman653. So please close it.

**Pull request closed without merging**
