### PR TITLE
fix: Changing language in TTS

### PR DESCRIPTION
**Pull request by chiragw15**
Fixes issue #853  
Added language to TTS

### CODE REVIEW

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Comment by chiragw15** [comment]
@chashmeetsingh @betterclever @amitiwary999 review please.

**Comment by mariobehling** [comment]
How is this setting stored on the server?

**Comment by chiragw15** [comment]
@mariobehling This is not a setting. The server provides a language attribute in response which represents the language of the answer. So, we have to you use it to specify TTS in which language it should give the output.

**Comment by mariobehling** [comment]
Ah, yes. But, we also need to follow up on the internationalization question. Will do that separately.

**Pull request merged**
