### PR TITLE
Fixes #240 Issue with Email field of login screen

### LINKED ISSUE #240: Issue with Email field of login screen
**Actual Behaviour**

On pressing the Enter key when email field is in focus, a new line is added and the text field extends.

**Expected Behaviour**

- [ ] The text field should not extend when Enter is pressed.
- [x] Remove hardcoded strings from activity_login.xml

**Steps to reproduce it**

1) Open Login Screen.
2) With the Email field in focus, press Enter key multiple times.

**Screenshots of the issue**

screenshot_20161017-231129

**Would you like to work on the issue?**

Yes, I would like to work on the issue.

### PR DESCRIPTION
**Pull request by VDenis**
Fixes issue #240 

Changes: now the text field don't extend when Enter is pressed. Remove hardcoded strings from activity_login.xml and add them to the strings.xml file.

Screenshot

### CODE REVIEW

**Comment by daminisatya** [comment]
@VDenis Thanks for the PR but can you squash your commits?

**Comment by daminisatya** [comment]
Also please attach a screenshot :)

**Comment by VDenis** [comment]
@daminisatya How can i squash my commits? I need close this pull request and make a new one with one commit?

**Comment by mariobehling** [comment]
Have a look here, please:

https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/ or here http://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

Cheers.

**Comment by VDenis** [comment]
@daminisatya @mariobehling Thanks for links. I did it.
1. Attach a screenshot,
2. Squash commits.

**Pull request merged**
