### PR TITLE
Implementing internationalization support

### LINKED ISSUE #866: Propose and implement internationalization support
What options are there?

### PR DESCRIPTION
**Pull request by amitiwary999**
Fixes #866 
Sub issue
1. added string.xml file for the German language
2. added string.xml file for the Spanish language
3. added string.xml file for the Italian language

Screenshots for the change:

### CODE REVIEW

**Comment by chiragw15** [comment]
@amitiwary999 Have you learnt german before or are you just using google translate and translating the strings. @mariobehling can you check if translations to german are fine?

**Comment by amitiwary999** [comment]
@mariobehling can you check it once. Some of my friend from different country helped me in this translation.

**Comment by mariobehling** [comment]
@amitiwary999 Thanks. It is not correct and we need to think this through more. Does this approach work with Weblate - weblate.org ?

**Comment by amitiwary999** [comment]
I will check how we can use [weblate](https://github.com/WeblateOrg/weblate) in our project.

**Comment by amitiwary999** [comment]
SUSI Android project is now hosted on weblate( [link](https://hosted.weblate.org/projects/susi-ai/android/) ).

**Comment by chiragw15** [comment]
@amitiwary999 In this PR have you translated string using weblate?

**Comment by amitiwary999** [comment]
These strings are translated by person from the respective country. We need to include weblate in our project then this translation can be uploaded on weblate and new translation can be downloaded from weblate site.

**Comment by chiragw15** [comment]
@amitiwary999 please finalize what is required with the weblate. I don't have much knowledge with that.

**Comment by amitiwary999** [comment]
@chiragw15 we need to add weblate service to our project as mentioned [here](https://docs.weblate.org/en/latest/admin/continuous.html#github-setup) and we need to add it as collabolator if we want weblate to push translations to our repository as mentioned [here](https://docs.weblate.org/en/latest/admin/continuous.html#hosted-push).

**Comment by chiragw15** [comment]
@amitiwary999 push a dummy commit to restart the checks. They are fixed now.

**Comment by amitiwary999** [comment]
@mariobehling I can't change settings of this repo. Can you add Weblate Service to this project as mentioned [here](https://docs.weblate.org/en/latest/admin/continuous.html#github-setup).

**Pull request merged**
