### PR TITLE
fixes issue #517

### PR DESCRIPTION
**Pull request by arp95**
made changes to certain items in strings.xml.

### CODE REVIEW

**Comment by mayank408** [comment]
Please follow the commit guidelines @arp95

**Comment by arp95** [comment]
@mayank408  not able to get you? Can you specify?

**Comment by jig08** [comment]
Read through [coding practices](https://github.com/fossasia/susi_android#code-practices) pls.

**Comment by jig08** [comment]
@arp95 You could have simple renamed your commit message.

**Pull request closed without merging**
