### PR TITLE
feat: Implement instrumentation test for device activity

### LINKED ISSUE #2351: Write unit test and instrumental test for device setup page
**Describe the feature you'd like**
Currently, no unit test and the instrumental test have been added to the smart speaker setup page. We need to have one to test for bugs.

**Additional context**
To enhance the workflow and make the app bug free

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by atm1504**
Fixes #2351 2351

Changes: 
Added instrumentation test for device activity

Screenshots for the change: 
No relevant UI changes

### CODE REVIEW

**Comment by iamareebjamal** [comment]
What is an implementation test?

Also, this test is useless

**Comment by atm1504** [comment]
> What is an implementation test?
> 
> Also, this test is useless

I wrote implementation test by mistake. I have corrected it. 
When I went through the code base under the test section, I found an instrumentation test is present for every almost every activity. So, I added this test for the device activity, which was missing.

**Comment by iamareebjamal** [comment]
Instrumention tests are not even being run on CI. Because they are useless. They are not testing anything

**Comment by atm1504** [comment]
> Instrumention tests are not even being run on CI. Because they are useless. They are not testing anything

Should I remove it from other activities also? Similar tests are present there also.

**Comment by iamareebjamal** [comment]
Let them be. They're not getting executed

**Comment by atm1504** [comment]
Okk, so I am closing this pr and the corresponding issue

**Pull request closed without merging**
