### PR TITLE
test: Adding auto updating of APK on appetize preview

### LINKED ISSUE #702: Setting the app on appetize.io for easy testing.
**Actual Behaviour**

Apk is not added to the pull request.

**Expected Behaviour**

Apk must be added after the pull request for easy testing.

### PR DESCRIPTION
**Pull request by chiragw15**
Fixes #702 

Changes: After merging of PR, the apk on appetize.io will be updated for testing.

### CODE REVIEW

**Comment by mariobehling** [comment]
Good job!

**Comment by mariobehling** [comment]
Please add info and link to the Readme.md as well.

**Comment by chiragw15** [comment]
@mariobehling Updated complete readme file adding information about MVP Pattern, new Screenshots, appetize.io auto updating preview, project structure etc.

**Comment by chiragw15** [comment]
@chashmeetsingh @betterclever @amitiwary999 review please.

**Pull request merged**
