### PR TITLE
Fixes #119 introduced espresso for unit testing.

### LINKED ISSUE #119: Unit test case - MainActivity view visibility
Can I write test cases ?
I will use Espresso for writing unit test cases.
Will start from checking presence of UI views
then gradually add methods to test different UI and navigation and features of the app.

This way I will also learn writing test cases.

### PR DESCRIPTION
**Pull request by abhi007tyagi**
Created new testing class TestMainActivity added 2 methods 
1. to test Visibility of views for main container.
2. to test Visibility of views for action bar.

Will add more test cases in future

Updated build.gradle 
1. for latest buildToolVersion and made minifyEnabled = true for release
2. for androidTestCompile imports

### CODE REVIEW

**Comment by jig08** [comment]
@abhi007tyagi TravisCI checks fail, pls look into this.

**Comment by abhi007tyagi** [comment]
There is some issue with Travis.
I have written a test case. It should not affect the build.

**Comment by jig08** [comment]
@abhi007tyagi 

Log:- 

```
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':app'.
> You have not accepted the license agreements of the following SDK components:
  [Android SDK Build-Tools 24.0.3].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
Total time: 1 mins 7.124 secs
The command "./gradlew build" exited with 1.
```

**Comment by abhi007tyagi** [comment]
Travis is trying to download the sdk and not able to accept license. Some one needs to configure the Travis for auto accept license agreement.

**Comment by jig08** [comment]
@mariobehling

>Some one needs to configure the Travis for auto accept license agreement.

**Comment by mariobehling** [comment]
> Travis is trying to download the sdk and not able to accept license. Some one needs to configure the Travis for auto accept license agreement.

Sure, please feel free to include the necessary in the pull request or let us know the specifics that need to be done from our side. Cheers.

**Comment by the-dagger** [comment]
That's not a problem with travis.
@abhi007tyagi Don't modify the gradle file unless and until its absolutely needed.
You have bumped up the build tool version to 24.0.3, where as the version that is specified to be used in travis.yml is 24.0.1, which is causing the build to fail.

**Comment by abhi007tyagi** [comment]
So, do I need to create a new PR? using 24.0.1?

**Comment by the-dagger** [comment]
Yeah, 
A better option is not to modify the default SDK and build tools version while sending a PR.
So just send a PR without modifying the default build tools or SDK.
You can always check for the defaults here 
[https://github.com/fossasia/susi_android/blob/master/.travis.yml#L7](https://github.com/fossasia/susi_android/blob/master/.travis.yml#L7)
Cheers.

**Comment by abhi007tyagi** [comment]
earlier it was 24.0.4 reverting it back!

**Comment by the-dagger** [comment]
Actually it was 24.0.2, so keep it that. :slightly_smiling_face:

**Pull request closed without merging**
