### PR TITLE
  Updated readme by adding naming conventions

### LINKED ISSUE #1368: Add a guide for naming conventions
**Actual Behaviour**

Currently, there are a number of different styles for naming variables, IDs, methods, classes etc. throughout the project. Thus, there is a non-uniform coding style throughout the project.

**Expected Behaviour**

Add a guide with naming conventions to be used in this project, so that all new contributors can refer to it. Also, the modifications can be made to the existing code accordingly.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by Bhavnaharitsa**
Fixes #1368 

Changes: Updated with proper naming conventions

### CODE REVIEW

**Comment by Bhavnaharitsa** [comment]
@iamareebjamal @arundhati24 @batbrain7 Please enlighten on this !!

**Comment by Bhavnaharitsa** [comment]
@batbrain7 sir any updates !!

**Comment by Bhavnaharitsa** [comment]
@iamareebjamal please review this too sir, there are many prs unreivewed .

**Comment by arundhati24** [comment]
> I think there is no problem with these on readme,
> @arundhati24 please enlighten?

I think currently there is too much to read on the README. Maybe we could create proper files and place them in the docs folder and provide relevant links in the README. I feel so because, for a person checking out the project for the first time, it might be too much to read for an introduction.

**Comment by Bhavnaharitsa** [comment]
> Lots of punctuation errors.

Shall check them

**Comment by Bhavnaharitsa** [comment]
> > I think there is no problem with these on readme,
> > @arundhati24 please enlighten?
> 
> I think currently there is too much to read on the README. Maybe we could create proper files and place them in the docs folder and provide relevant links in the README. I feel so because, for a person checking out the project for the first time, it might be too much to read for an introduction.

I felt the same too. If there's any future implementation like providing links I would love to work on it

**Comment by iamareebjamal** [comment]
@atm1504 Please fork and create a new PR

**Comment by atm1504** [comment]
@iamareebjamal I will surely do it sir

**Comment by mariobehling** [comment]
Out of scope for the Readme.

**Pull request closed without merging**
