### PR TITLE
Feat: make speech input full screen 

### LINKED ISSUE #856: Make Speech input full Screen
Follow Siri and Cortana and implement a full-screen Speech input feature.

### PR DESCRIPTION
**Pull request by amitiwary999**
Fixes #856 

https://drive.google.com/file/d/0B8gIkH5cqXi3T2pOUk9fMTFTQWc/view?usp=sharing
problem is that we can't show partial text but it is similar like Siri.

I made another UI
https://drive.google.com/file/d/0B8gIkH5cqXi3dlMxcE1GUEFNZ0k/view?usp=sharing

### CODE REVIEW

**Comment by amitiwary999** [comment]
@mariobehling please it. we need this feature urgently. This flow is correct or not. Link for demo video is provided in the comment.

**Comment by chiragw15** [comment]
@amitiwary999 Can you implement this and change colors to shades of blue 
https://drive.google.com/file/d/0B8gIkH5cqXi3dlMxcE1GUEFNZ0k/view?usp=sharing

**Comment by amitiwary999** [comment]
@chiragw15 change color of all bars to blue?

**Comment by chiragw15** [comment]
Combination of different shades of blue and gray instead of black and brown,

**Comment by amitiwary999** [comment]
@chiragw15 review.

**Comment by chiragw15** [comment]
Awesome work @amitiwary999 :smile: Just one little thing. Change the color of the right most bar. Also add new screencast so Mario can have a look at it once too.

**Comment by amitiwary999** [comment]
@chiragw15 thanks. If you suggest color code then it will be better. thanks

**Comment by chiragw15** [comment]
Three shades of blue for three blue bars #4184f3, #0000d4 and #0091ea . Keep colors of gray bars same.

**Comment by chashmeetsingh** [comment]
Looks good 👍

**Comment by mariobehling** [comment]
How is that different from Google Assistant or Siri? I see the text is very small and the moving sound image is very much at the bottom. How is that with the other assistants? Can you make it closer to them, please?

**Comment by amitiwary999** [comment]
@mariobehling UI is similar like Cortana. But animation is different from that. When the user starts speaking then bars move up and down and when finished then rotate to show that speech input is finished and after that, we show chat.

**Comment by amitiwary999** [comment]
image

**Comment by mariobehling** [comment]
Where is the sound - speaking - button in the full screen mode like with Siri?

**Comment by amitiwary999** [comment]
sound speaking button is in front page as soon as user click on it, animation starts with full-screen speech input and once user finished speaking it shows chat activity where mic button is present.

**Comment by mariobehling** [comment]
ok, let's try this out.

**Pull request merged**
