### PR TITLE
fix: Changed color to the heading in privacy fragment 

### PR DESCRIPTION
**Pull request by Bhavnaharitsa**
Fixes : #2159  
Changes: The headings in privacy fragment are in black color and the space between heading and content is very less. So, in order to differentiate, I have made the headings of privacy fragment to blue.
Screenshots for the change: 

image

### CODE REVIEW

**Comment by Bhavnaharitsa** [comment]
@batbrain7 @iamareebjamal please review

**Comment by immadisairaj** [comment]
@Bhavnaharitsa please follow semantic guidelines.

**Comment by immadisairaj** [comment]
@Bhavnaharitsa Every PR should link the Issue which it fixes.

**Comment by Bhavnaharitsa** [comment]
I'm sorry this is a minor thing so I just made a pull request

**Comment by iamareebjamal** [comment]
GitHub won't let me merge until you add a semantic PR and link the issue :(

**Comment by Bhavnaharitsa** [comment]
@iamareebjamal Changed !! Can you please merge this now ?

**Comment by immadisairaj** [comment]
> Fixes : #2153
How can a PR fix PR?

**Comment by Bhavnaharitsa** [comment]
> > Fixes : #2153
> 
> How can a PR fix PR?

typo!

**Comment by Bhavnaharitsa** [comment]
@iamareebjamal Please merge this !!

**Pull request merged**
