### PR TITLE
Fixes #25 : Added butterknife

### LINKED ISSUE #25: Add butterknife for faster development

### PR DESCRIPTION
**Pull request by code-crusher**
Added butterknife for faster development.
Fixes issue #25

### CODE REVIEW

**Comment by daminisatya** [comment]
@code-crusher Help us follow the best practice :)  your commit message must include the issue number which will auto closes the issue on code merge. 
```Fixes #<issue number> : <meaningful commit message>``

**Comment by code-crusher** [comment]
@daminisatya thank you for the suggestion. I have updated it :)

**Comment by daminisatya** [comment]
+1

**Comment by the-dagger** [comment]
Looks good, merging

**Pull request merged**
