### PR TITLE
Fixes #73 : speech to text updated

### LINKED ISSUE #73: Using speech to text to take the input
how it would be to use speech to text input in the app..
i would like to work on that....

### PR DESCRIPTION
**Pull request by mayank408**

### CODE REVIEW

**Comment by amitiwary999** [comment]
try to add all files you have changed including drawable.

**Comment by jig08** [comment]
@mayank408 
* Squash your commits into a single one.
* Use the format `Fixes #<issue number> : <commit message>` to maintain the project development and maintenance flow.

**Comment by daminisatya** [comment]
@mayank408 Any update over here?

**Comment by mayank408** [comment]
@jig08 @daminisatya Mam I am in first year and still learning to use git and github thats why I am facing problem though the app is running smoothly with speech to text update but I am facing problem in squashing the commits and resolving conflicts.

**Comment by daminisatya** [comment]
@mayank408 no worries! (No Mams please :P) 
There are two ways in which you can squash.
* While pushing another commit, you can amend to the previous commit. ```git commit --amend``` (when you already have a commit existing and you want to amend to it) instead of doing ```git commit -m "message"``` every time.

* But then you dint follow the above amending rule, and you pushed multiple commits (like how you have done now) You can squash everything into one single commit. Check your ```git log``` and decide on till where you want to squash. suppose there are 2 commits of yours which you want to squash into single, then the command goes ```git rebase -i HEAD~2```. Which leads to an editor where you will be asked for every commit whether you want to pick to squash. type squash for all the 2 commits present and exit. The rebase continues and you have force push the changes, as in ```git push -f origin <branch>```. 

This might be a bit confusing, but please watch this [video](https://www.youtube.com/watch?v=qh9KtjfjzCU)

**Comment by daminisatya** [comment]
Coming to conflicts. You have be careful with these. One way to avoid the conflicts is to
* Save your changes in the branch by using ```git stash``` 
* Then pull the latest changes ```git pull origin master```
* And then apply your saved changes ```git stash apply```
* Now comes the main part where you can view your merge conflicts. Git will tell you in which file you are facing the conflict and you need to resolve in that file (where it specifies where the develop's head is and where's your changes are) 

Please watch[ this video ](https://www.youtube.com/watch?v=g8BRcB9NLp4)on how you can clear of the conflicts

**Comment by daminisatya** [comment]
So you can take it slow but we want the best practice :)

**Pull request closed without merging**
