### PR TITLE
Fix #512 delay in TTS fixed

### LINKED ISSUE #512: Output of text to speech delayed (very slow)
Speech to text is fast, but text to speech is slow. Text to voice has 15-20 seconds delay of answers. The server response is quick. So this is not a server issue. Please check what is the reason for the delay and help to fix it.

### PR DESCRIPTION
**Pull request by viveksb007**
Fixes issue #512 

Changes: TextToSpeech.OnInitListener() delays for the first time. So initialised it in the beginning itself. It fixed the delay. And reformatted the code.

Screenshots for the change:

### CODE REVIEW

**Comment by betterclever** [comment]
@viveksb007 Can you provide sample apk?

**Comment by viveksb007** [comment]
ya sure
https://drive.google.com/open?id=0B30IF3fyX4Q3LVloVzluaVJlbnM

**Comment by Orbiter** [comment]
@viveksb007 your code looks good. @betterclever have you tested the app? If it works, please merge the commit

**Comment by betterclever** [comment]
@Orbiter @viveksb007 The apk provided is crashing when I try to initiate speech input.
Exact logcat:

03-04 12:42:04.612 7762-7762/org.fossasia.susi.ai E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: org.fossasia.susi.ai, PID: 7762
                                                                    android.util.AndroidRuntimeException: Unknown error code -8 when starting Intent { act=android.speech.action.RECOGNIZE_SPEECH (has extras) }
                                                                        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1840)
                                                                        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1525)
                                                                        at android.app.Activity.startActivityForResult(Activity.java:4225)
                                                                        at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
                                                                        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
                                                                        at android.app.Activity.startActivityForResult(Activity.java:4183)
                                                                        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
                                                                        at org.fossasia.susi.ai.activities.MainActivity.promptSpeechInput(MainActivity.java:289)
                                                                        at org.fossasia.susi.ai.activities.MainActivity.access$400(MainActivity.java:113)
                                                                        at org.fossasia.susi.ai.activities.MainActivity$13.onClick(MainActivity.java:616)
                                                                        at android.view.View.performClick(View.java:5637)
                                                                        at android.view.View$PerformClick.run(View.java:22433)
                                                                        at android.os.Handler.handleCallback(Handler.java:751)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6176)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)

**Comment by viveksb007** [comment]
@betterclever its working fine in my phone ( Android 6.0.1 ).

Anyways there is some problem in speech input. What my code is doing is calling TextToSpeech.OnInitListener() in the beginning as it takes time during the first call.

temp

Can you check if speech input is working on your phone in susi app (not my sample apk)?
And if its working add [compensateTTSdelay()](https://github.com/fossasia/susi_android/pull/532/files#diff-97eb5665ef5431161882b9bd50d1843d) function and check it again?

Please confirm your findings.

**Comment by betterclever** [comment]
Sure. I'll check and confirm. But it won't be possible now, I'm having
exams. I'll confirm by 6 March.

**Comment by Orbiter** [comment]
How can we proceed here, there are only a few days left until fossasia!

**Comment by viveksb007** [comment]
@Orbiter I think we can go ahead and merge this PR as its intended to fix the delay in text to speech which can be checked by sending the text and getting output as speech, if taking input as speech isn't working.

The problem/crash @betterclever is referring to is in input as a speech. We can raise another issue for improving input as a speech.

**Comment by betterclever** [comment]
@Orbiter  I noticed the bug is due to another reason. It is working fine
currently. I'll root out the reason for that shortly. No delay is present
in speech output. This can be merged.

**Comment by Orbiter** [comment]
+1

**Pull request merged**
