### PR TITLE
Fixes issue #266: Adding received ticks

### PR DESCRIPTION
**Pull request by chiragw15**
Fixes issue #266 
Changes: Added received ticks.

Screenshots for the change: 

1.) Not received by susi
screenshot_20161125-195319 1

screenshot_20161125-195319

2.) Replied by susi

screenshot_20161125-195155 1

screenshot_20161125-195155

### CODE REVIEW

**Comment by mariobehling** [comment]
Thanks. Currently Circle CI is failing. Please check.

**Comment by chiragw15** [comment]
@the-dagger can you please help me with this?

**Comment by the-dagger** [comment]
Sure, let me have a look.

**Comment by chiragw15** [comment]
@the-dagger thanks :)

**Pull request merged**
