### PR TITLE
Remove unused susi response file (Fixed #1627)

### LINKED ISSUE #1627: Unused susi response file
**Actual Behaviour**

There is an unused response file called 'Skills'.

**Expected Behaviour**

Remove unused file.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by arundhati24**
Fixes #1627

### CODE REVIEW

**Comment by batbrain7** [comment]
This api maybe used in the future, we never when the flow can change, removing this is not such a good option

**Comment by arundhati24** [comment]
This is not an API. This is a response file. For your information, this will not be used. Instead filteredData array is used everywhere now. Hence, this is not needed.

**Comment by arundhati24** [comment]
@batbrain7 I resolved the conflicts.
@iamareebjamal As this PR is leading to unnecessary conflicts in every PR, can this be merged if it is fine?

**Comment by iamareebjamal** [comment]
@batbrain7 Please don't use Request Changes for asking for conflict resolution because then I have to dismiss the review. Github automatically doesn't allow merging until conflicts are resolved, just use a single comment

**Pull request merged**
