### PR TITLE
Add butterknife to signup

### PR DESCRIPTION
**Pull request by rathodchintan**
Changes: [Add butterknife clicking to signup in Login screen. Remove TextView & click listener.]

### CODE REVIEW

**Comment by mariobehling** [comment]
Which issue is this? Where has this been discussed? Each PR needs to match an issue, please.

**Comment by rathodchintan** [comment]
There is no issue but i just optimize the code.

**Comment by mariobehling** [comment]
Sorry, this is not our workflow. The contributor base is big and we are loosing track if we are merging lots of issues without issues. Every PR needs to be merged to an issue. Please open an issue and give devs a chance to give input if they want. Please open an issue for this PR and match the PR with the issue.

**Comment by mariobehling** [comment]
@rathodchintan A pity, you did not follow the workflow. I am merging this now as it is useful. It would be really good, if you could help and make it easier in future for everyone to involve and review by following the flow. Cheers.

**Comment by rathodchintan** [comment]
@mariobehling Thanks. I will follow the flow from next pull. :)

**Pull request merged**
