### PR TITLE
fix: Close chat search if user wants

### LINKED ISSUE #2155: Chat Search cannot be closed once opened
**Describe the bug**
Currently there is no way to close chat search, if the user opens it once and tries to close it without searching anything.

**Expected Behaviour**
User should be able to close the chat search if he don't want to search anything. This could be done by clicking on search icon once again.

**Steps to reproduce it**
* Click on search icon in Chat Activity.
* The search text edit does not become invisible once opened, without searching anything.

**Screenshots of the issue**
Screenshot 2019-04-10 at 8 12 15 PM

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by atm1504**
Fixes #2155 

Changes: 
* Changed the if else condition in button press.

Screenshots for the change: 
close

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Why these bugs aren't apparent when sending PR

**Comment by iamareebjamal** [comment]
Change search icon color to white

**Comment by atm1504** [comment]
> Why these bugs aren't apparent when sending PR

Sorry sir. I didn't saw this bug. I came to know about it, when one of my friend informed me that about this.

**Comment by atm1504** [comment]
> Change search icon color to white

okk sir

**Pull request merged**
