### PR TITLE
chore: Updated naming convention

### LINKED ISSUE #1368: Add a guide for naming conventions
**Actual Behaviour**

Currently, there are a number of different styles for naming variables, IDs, methods, classes etc. throughout the project. Thus, there is a non-uniform coding style throughout the project.

**Expected Behaviour**

Add a guide with naming conventions to be used in this project, so that all new contributors can refer to it. Also, the modifications can be made to the existing code accordingly.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by atm1504**
Fixes #1368

Changes: Updated with proper naming conventions

### CODE REVIEW

**Comment by atm1504** [comment]
@iamareebjamal @batbrain7 @arundhati24  I made this pr by making suggested changes that were asked in #2066 
Circle ci was not triggered in that pr. Please review it.

**Comment by atm1504** [comment]
@iamareebjamal its the same issue as in #2066 
Circle ci is not being triggered here also. I have already applied build check locally and it worked properly. I think there is surely some problem related to cicircle on chore related pr.

**Comment by atm1504** [comment]
@iamareebjamal please review it. It is against the pr #2066 which was not passing the circle build.

**Comment by mariobehling** [comment]
Out of scope for Readme.

**Pull request closed without merging**
