### PR TITLE
Removed hard coded strings in MainActivity

### PR DESCRIPTION
**Pull request by madhavrathi**
Fixes issue #587

Changes: Hard Coded strings were removed.

### CODE REVIEW

**Comment by chiragw15** [comment]
@madhavrathi There are more hardcoded strings in Other Activities too like Login Activity, etc. It would be nice if you remove them too and add them to strings.xml file. Also, please follow the commit message guidelines https://github.com/fossasia/susi_android#code-practices .

**Comment by madhavrathi** [comment]
@chiragw15 Sure. will update PR soon and follow commit message guidelines

**Comment by chiragw15** [comment]
@madhavrathi can you please resolve conflicts.

**Comment by madhavrathi** [comment]
@mayank408 These are merge commits and can be squashed while merging. do you still suggest that i should do it from my end ?

**Comment by madhavrathi** [comment]
@chiragw15 Sure. I'll update the PR

**Comment by madhavrathi** [comment]
Closing this for mean while. Will Update and send PR

**Pull request closed without merging**
