### PR TITLE
fix: UI of Login, Signup and forgot PW Screen

### PR DESCRIPTION
**Pull request by chiragw15**
Fixes part of issue #857 

.

.

.

.

.

.

.

.

.

.

.

### CODE REVIEW

**Comment by chiragw15** [comment]
@betterclever @amitiwary999 @chashmeetsingh review please

**Comment by chashmeetsingh** [comment]
The login button in screenshot 2 looks compressed. Also, IMO having the buttons width same as the text fields would look much better.

**Comment by chiragw15** [comment]
@chashmeetsingh done.

**Comment by mariobehling** [comment]
Instead of two buttons - SUSI.AI server and Personal server -, provide one button with a tick box "Customer Server". Once the user clicks on the button **in the same area** (on the same line/same space) of the words "Customer Server" now show a field for the URL input.

**Comment by chiragw15** [comment]
Included this in #875

**Comment by chiragw15** [comment]
fixed in #875

**Pull request closed without merging**
