### PR TITLE
Unit Test Cases to check Visibility of Views

### PR DESCRIPTION
**Pull request by abhi007tyagi**
I am not able to squash these three commits at this moment as they were pushed to my branch and I had already rebased with the base fork.
Please merge these changes to the base fork.
Will keep send single commits from next time.

### CODE REVIEW

**Comment by abhi007tyagi** [comment]
Is there any emulator or device attached with Travis?

**Comment by abhi007tyagi** [comment]
@the-dagger what is the purpose of `-no window ` in the Travis yml script `- emulator -avd test -no-skin -no-audio -no-window &` ?

**Comment by the-dagger** [comment]
@abhi007tyagi The connected tests are failing.
[https://travis-ci.org/fossasia/susi_android/builds/166326747#L2292](https://travis-ci.org/fossasia/susi_android/builds/166326747#L2292)
```
org.fossasia.susi.ai.TestMainActivity > testUIViewsPresenceOnLoad[test(AVD) - 7.0] FAILED 
	java.lang.RuntimeException: Waited for the root of the view hierarchy to have window focus and not be requesting layout for over 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Otherwise, something is seriously wrong. Selected Root:
	Root{application-window-token=android.view.ViewRootImpl$W@75a416d, window-token=android.view.ViewRootImpl$W@75a416d, has-window-focus=false, layout-params-type=1, layout-params-string=WM.LayoutParams{(0,0)(fillxfill) sim=#103 ty=1 fl=#81810100 wanim=0x1030465 needsMenuKey=2}, decor-view-string=DecorView{id=-1, visibility=VISIBLE, width=320, height=480, has-focus=true, has-focusable=true, has-window-focus=false, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2}}
org.fossasia.susi.ai.TestMainActivity > testActionBarViewsPresenceOnLoad[test(AVD) - 7.0] FAILED 
	java.lang.RuntimeException: Waited for the root of the view hierarchy to have window focus and not be requesting layout for over 10 seconds. If you specified a non default root matcher, it may be picking a root that never takes focus. Otherwise, something is seriously wrong. Selected Root:
	Root{application-window-token=android.view.ViewRootImpl$W@55607c8, window-token=android.view.ViewRootImpl$W@55607c8, has-window-focus=false, layout-params-type=1, layout-params-string=WM.LayoutParams{(0,0)(fillxfill) sim=#103 ty=1 fl=#81810100 wanim=0x1030465 needsMenuKey=2}, decor-view-string=DecorView{id=-1, visibility=VISIBLE, width=320, height=480, has-focus=true, has-focusable=true, has-window-focus=false, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=2}}
:app:connectedDebugAndroidTest FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:connectedDebugAndroidTest'.
> There were failing tests. See the report at: file:///home/travis/build/fossasia/susi_android/app/build/reports/androidTests/connected/index.html
```   
Also yeah there is indeed an AVD attached on which the connected tests are being ran upon.

**Comment by abhi007tyagi** [comment]
What is `-no window `in yml?
I think UI is not getting visible and that's why this test is failing.
In the test, I am testing if all the items are getting displayed on the screen.

**Comment by the-dagger** [comment]
No, the problem was that you were trying to run the tests while device was locked.
I have added `adb shell input keyevent 82` to travis.yml before the tests so that the device is unlocked before tests are ran on it.

**Comment by abhi007tyagi** [comment]
yeah.. just checked a similar issue here
https://github.com/travis-ci/travis-ci/issues/6340

**Comment by the-dagger** [comment]
Checks are passing now.
@abhi007tyagi Please squash the commits and I'll merge the PR :+1: 
More on how to squash is here : [http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit](http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit)
Cheers.

**Pull request closed without merging**
