### PR TITLE
feat: Display connected devices

### LINKED ISSUE #1652: Add layout to view connected devices
**Actual Behaviour**

There is no layout for the devices section when the device is successfully connected to the server

**Expected Behaviour**

Add the layout to view connected devices.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by atm1504**
Fixes #1652 

### Checkpoints
- [x] Add the entire UI
- [x] Fetch the data from the server
- [x] Display the fetched data

### CODE REVIEW

**Comment by mariobehling** [comment]
It is the end of GSoC term 1: You still don't know about our Best Practices? Include screenshots and test APK with every PR! Reviewing your PRs takes a long time, because you don't follow standard developer practices.

**Comment by atm1504** [comment]
> It is the end of GSoC term 1: You still don't know about our Best Practices? Include screenshots and test APK with every PR! Reviewing your PRs takes a long time, because you don't follow standard developer practices.

This is a long pr and it's not completed yet. It has been marked as work in progress. So, screenshot and apk has not been attached.

**Comment by batbrain7** [comment]
@atm1504 where are you stuck ?

**Comment by atm1504** [comment]
> @atm1504 where are you stuck?

@batbrain7 
The data classes that I wrote is failing to parse the JSON response that it receives. Mainly the device portion. Link: https://api.susi.ai/aaa/listUserSettings.json?access_token=XdRM8stxKYHpbLTYiPxgXEj6paI52L&fbclid=IwAR2LlZ4_y3cakppb-gOc18xsZrn-bUGq8iPZHZfYtkvFM6R-iQNhJ2j7eug

Screenshot 2019-06-26 at 1 32 02 PM

**Comment by iamareebjamal** [comment]
Because `devices` is not a list of Device object. Read about JSON types

**Comment by atm1504** [comment]
Screenshot: 
ezgif com-video-to-gif


Apk : 
[app-fdroid-debug.apk.zip](https://github.com/fossasia/susi_android/files/3330705/app-fdroid-debug.apk.zip)

**Comment by atm1504** [comment]
@iamareebjamal @batbrain7 @arundhati24 please review it

**Comment by atm1504** [comment]
@iamareebjamal @batbrain7 @arundhati24 please review it

**Pull request merged**
