### PR TITLE
fix: Improve the skill details view for landscape

### LINKED ISSUE #1673: Improve the skill details view for landscape orientation
There is a need to check the UI of the skill details screen on changing the screen orientation.

**Screenshots of the issue**

img_20180819_123004_970

img_20180819_122924_104

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by aleronarjun**
Change placement of UI elements to better use screen estate.

Fixes #1673 

Changes: 

Placement of some elements has been changed, along with some margin/padding values being adjusted for landscape view. Layouts have been added/adjusted wherever necessary to achieve desired result.

Screenshots for the change: 

Before:

screenshot_1537887751

screenshot_1537887759

After:

screenshot_1537887390

screenshot_1537887403

### CODE REVIEW

**Comment by aleronarjun** [comment]
@arundhati24 
Please review this. Thanks!

**Comment by arundhati24** [comment]
@aleronarjun I feel that the 'Try it' and 'Share' button should remain as they are. I don't think they should be moved towards the end. 
The feedback and the skill rating are two different sections in the portrait view, hence, the feedback from various users is shown under feedback section, but, in the modified landscape view, you have changed the position of feedback from different users. You have moved it to the skills rating section. Also, will this change appear consistent across different screen sizes?
Can we make some improvements to the changes proposed by you? Do you have more suggestions?

**Comment by iamareebjamal** [comment]
Please see the Semantic Pull Request check, so we can merge this PR. Nice Work!

**Comment by iamareebjamal** [comment]
Should be feat

**Pull request merged**
