### PR TITLE
Fixed #69 search functionality completely added

### LINKED ISSUE #69: Addition of Search Functionality in messages
Now that messages are being stored in database, PR #66 , searching in messages can be done to highlight that particular message in the conversation.

### PR DESCRIPTION
**Pull request by viveksb007**
searches and scrolled to latest message with search query.

ToDo : 

- ~~highlight message searched by changing its background.~~
- ~~add up,down image buttons sided with searchView to see more search results.~~

### CODE REVIEW

**Comment by daminisatya** [comment]
@viveksb007 Can you add the screenshots demonstrating it.

**Comment by the-dagger** [comment]
@viveksb007 Update the PR by adding the todo items and I'll merge it. :+1:

**Comment by viveksb007** [comment]
@gogeta95 can you suggest a way to change background of a particular message in recyclerView?
changing from onBindViewHolder is changing background of all messages inspite of doing this
`
@Override
    public void onBindViewHolder(ChatViewHolder holder, int position) {
        handleItemEvents(holder, position);
        if (highlightMessagePosition == position) {
            holder.itemView.setBackgroundColor(Color.BLACK);
            highlightMessagePosition = 0;
        }
    }

`
reference : MainActivity.java ( line 242 )

**Comment by gogeta95** [comment]
@viveksb007 you have to mention an `else` condition after your `if` condition because recyclerview actually recycles items which are already turned black, then calls `onbindviewholder`on each, and absence of else statement keeps them black(recycled). hence all become black.

**Comment by mariobehling** [comment]
@viveksb007 Good job so far. Please help to resolve the issues. Cheers.

**Comment by viveksb007** [comment]
@the-dagger search functionality completely implemented

**Comment by the-dagger** [comment]
@viveksb007 Looks awesome!
Can you add a bit more alpha to the selector color?
The black color looks weird with the current design.
Keep it as a lighter shade of Primary Color.
Also Please remove the merge conflicts so that I can merge this PR.
Cheers.

**Comment by viveksb007** [comment]
@the-dagger color changed and conflicts resolved

**Comment by the-dagger** [comment]
Looks good. 
We can make the other ui enhancements later on. 
Thanks!

**Pull request merged**
