### PR TITLE
Make release for version 11

### PR DESCRIPTION
**Pull request by batbrain7**
Changes: To be merged after testing the apk

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Guys finalize this, what's the issue @batbrain7 @arundhati24

**Comment by arundhati24** [comment]
@iamareebjamal There were some discussions on Gitter about some changes (e.g. in About Us fragment) that were needed before releasing the version. That's why this was on hold. @batbrain7 Do we need to make any more changes?

**Comment by arundhati24** [comment]
For me the app works fine. @batbrain7 Is it the same for you too after the new changes?

**Comment by batbrain7** [comment]
It works fine for me too

**Pull request merged**
