### PR TITLE
fix: transfered help,privacy,about us to settings

### LINKED ISSUE #2152: Transfer Privacy, Help and About us to Settings
**Describe the feature you'd like**
Currently, the app has privacy, help and about us fragments in menu bar which is not required. Menu bar is filled with items . We can only constraint the menu bar with login,signup(which disables after login) and settings. and tranfer the privacy, help and about us to settings because in any legit app, the user would go to the settings in order to find these docs

**Screenshots**

image

@iamareebjamal Please opine on this 

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by Bhavnaharitsa**
Fixes #2152 

Changes:Transfered about us, help and privacy from menu bar to settings

Screenshots for the change: 
Screenshot_20190413-070753_SUSIAI

Screenshot_20190413-070759_SUSIAI

### CODE REVIEW

**Comment by Bhavnaharitsa** [comment]
@iamareebjamal Sorry, I had to close the previous pull request because my system crashed and some files were deleted. I had to do everything from scratch. Please pardon me.

**Comment by iamareebjamal** [comment]
You still could just push to the same branch

**Comment by Bhavnaharitsa** [comment]
@iamareebjamal please review!!

**Comment by iamareebjamal** [comment]
Circle CI and SPR not completed

**Comment by Bhavnaharitsa** [comment]
Done, please review it now!! @iamareebjamal

**Comment by iamareebjamal** [comment]
Still not done

**Comment by Bhavnaharitsa** [comment]
@iamareebjamal How can I check what's the problem with circle ci?

**Comment by atm1504** [comment]
> @iamareebjamal How can I check what's the problem with circle ci?

@Bhavnaharitsa apply ./gradlew spotlessApply in terminal locally. This will prompt out the errors that you might have related to circleci. Also it fixes indentation error automatically.

**Comment by Bhavnaharitsa** [comment]
> > @iamareebjamal How can I check what's the problem with circle ci?
> 
> @Bhavnaharitsa apply ./gradlew spotlessApply in terminal locally. This will prompt out the errors that you might have related to circleci. Also it fixes indentation error automatically.

Thanks! :D

**Comment by iamareebjamal** [comment]
@atm1504 Please fork and create a PR

**Comment by atm1504** [comment]
@iamareebjama @arundhati24 @batbrain7  please close it. This issue has already been solved.

**Pull request closed without merging**
