### PR TITLE
Added About Section

### LINKED ISSUE #898: Add "About Section"
Add a about section section adding following information.
1. About SUSI
2. Adding github link of this repo for reporting bug.
3. Add link to skill cms (http://skills.susi.ai/) for editing and creating skills.
4. Add licence information.

eg.

### PR DESCRIPTION
**Pull request by Prashant-Chaurasia**
Fixes #898 

Changes: Made "About Us" section using a fragment.

Screenshots for the change: 

screenshot_20170913-120309
screenshot_20170913-120315

### CODE REVIEW

**Comment by Prashant-Chaurasia** [comment]
@chiragw15 Is this good ?

**Comment by mariobehling** [comment]
Please take out the circle with the gear wheels and resolve merge conflicts. Thanks!

**Comment by chiragw15** [comment]
@Prashant-Chaurasia Not looking good imo. Can you once try removing cards and compare with current layout and see if it looks better.

**Comment by Prashant-Chaurasia** [comment]
@mariobehling @chiragw15 Is this looking good? @chiragw15 It was not looking nice when I removed the cards , also I have modified it a bit.

Screenshots:
screenshot_20170914-234914
screenshot_20170914-234919

**Comment by mariobehling** [comment]
Ok, let's iterate from here. Cheers.

**Pull request merged**
