### PR TITLE
fix: Speech to text button on chat activity not working #2469

### LINKED ISSUE #2469: Speech to text button on chat activity not working
**Describe the bug**
If you press the back button during voice recognition, the 'Speech to text' button becomes unclickable and also SUSI skills button, google assistant button, and search button becomes invisible.

**Screenshots of the issue**

ezgif com-video-to-gif

**Smartphone Info:**
|Device         | Redmi K20 |
|Android Version| Q 10.0|

**Would you like to work on the issue?**

yes, I would like to

### PR DESCRIPTION
**Pull request by shubhamkumar1739**
Fixes #2469 Speech to text button on chat activity not working

Changes: Add function restoreActivityState() to make invisible views visible

### CODE REVIEW

**Comment by shubhamkumar1739** [comment]
My circleci build is failing. Please help : 
Screenshot from 2020-02-05 18-45-30

**Review by mkmar01 — COMMENTED** [review]
Check the failing CI build

**Comment by shubhamkumar1739** [comment]
i dont understand why im getting authentication failed. Please help

**Comment by iamareebjamal** [comment]
Don't create PRs from development branch

**Pull request closed without merging**
