### PR TITLE
Change the proportion of logo to fit with the acual logo proportion

### PR DESCRIPTION
**Pull request by mayank408**
Fixes issue #829

Changes: Change the proportion of logo to fit with the actual logo proportion

screenshot_1499845974

### CODE REVIEW

**Comment by mariobehling** [comment]
The screenshot shows that it is still stretched.

**Comment by mayank408** [comment]
@mariobehling Pls see this

screenshot_1499849257

**Comment by mayank408** [comment]
screenshot_1499849513

**Comment by mayank408** [comment]
@mariobehling Pls tell which of the above two is correct.

**Comment by mayank408** [comment]
Pls see this @mariobehling 

screenshot_1499850010

**Comment by mariobehling** [comment]
Yes, seems fine now. Thanks.

**Pull request merged**
