### PR TITLE
Changed App name to SUSI AI

### PR DESCRIPTION
**Pull request by RaiVaibhav**
Fixes #[1006](https://github.com/fossasia/susi_android/issues/1006)

Changes: [Changed App name to 'SUSI AI']

### CODE REVIEW

**Comment by RaiVaibhav** [comment]
@collinx @iamareebjamal  sir currently i saw that @aditya98ak already made a PR regarding this issue but after that also issue is open.
I really don't understand that

**Comment by collinx** [comment]
@RaiVaibhav that PR has not been merged till now, that's why the issue #1006 is open.

**Comment by RaiVaibhav** [comment]
@collinx ok sir  thanks i did't see in hurry that @aditya98ak already made a PR and created a PR ,as i am absolute beginner,hope u understand what i want to say.

**Comment by RaiVaibhav** [comment]
@collinx  i don't know what is going on, help me i am new in open source, i just updated my strings.xml file and remove the susi after string and it showing failed on ci

**Comment by iamareebjamal** [comment]
@RaiVaibhav The issue is already fixed by #1007 

Thanks :smile:

**Comment by collinx** [comment]
@RaiVaibhav issue #1006 is fixed. Open a new issue for changing occurrence of susi in the string.xml, and edit this PR to reference that new issue. 😄

**Comment by RaiVaibhav** [comment]
@collinx i find that i made a wrong commit, issue is already solve 

Thanks

**Pull request closed without merging**
