### PR TITLE
Add dark theme to SUSI [WIP]

### LINKED ISSUE #1216: No Dark theme like web
**Actual Behaviour**
Presently there is no dark theme for the Android app like the web has.

**Expected Behaviour**
Must have a dark theme

**Screenshots of the issue**
dark

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by DipanshKhandelwal**
Fixes #1216 

## Add dark theme for the app

Screenshots of the change: 
dark ai susi
light ai susi

### CODE REVIEW

**Comment by DipanshKhandelwal** [comment]
@mariobehling @Orbiter

**Comment by mariobehling** [comment]
Looks fine to me.

**Comment by iamareebjamal** [comment]
@chiragw15 Should this be closed?

**Comment by chiragw15** [comment]
@DipanshKhandelwal please resolve conflicts and ask co-developers to review the PR

**Comment by DipanshKhandelwal** [comment]
Sorry, I didn't check it for a while, I'll do the required changes asap.

**Comment by DipanshKhandelwal** [comment]
@Orbiter and due to very quick updates in the repository it also needs a quick rebase for someone to check, how can that be handled?

**Comment by batbrain7** [comment]
@DipanshKhandelwal the conflict is resolved is the PR still WIP ?

**Comment by mariobehling** [comment]
Closing this due to inactivity.

**Pull request closed without merging**
