### PR TITLE
Release new version for fdroid and playstore

### PR DESCRIPTION
**Pull request by batbrain7**
Changes: Update the master branch with the dev branch.

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Check why build is failing

**Comment by batbrain7** [comment]
the line` bash exec/apk-gen.sh` is not executed properly

**Comment by batbrain7** [comment]
screen shot 2018-06-16 at 7 44 53 pm

**Comment by batbrain7** [comment]
this was a problem last time too when the script had too be updated

**Comment by iamareebjamal** [comment]
Then please fix it

**Comment by batbrain7** [comment]
@iamareebjamal please merge

**Comment by batbrain7** [comment]
@iamareebjamal how to make sure changes are updated on the playstore ?

**Pull request merged**
