### PR TITLE
fix: 1022 welcome description overlap

### PR DESCRIPTION
**Pull request by anandwana001**
fix: #1022  Welcome description overlapping on screen less than 5"

### CODE REVIEW

**Comment by collinx** [comment]
@anandwana001 Resolve conflicts and push again. Also, try to add commits related to the issue in a PR. 😄

**Comment by anandwana001** [comment]
@collinx facing problem in PR. I will be resolving these soon.

**Comment by anandwana001** [comment]
It seems like my different commit gets include in this PR!! Is there any way we can remove these commits or I have to make a new pull request? Need some help as I am new to these things!!!

**Comment by collinx** [comment]
@anandwana001 you should make a new branch for each PR as it takes time to review and merge PRs. Also, for now, force push only this PR's commit but I recommend later option.
reset development branch, checkout in the new branch, make changes in that branch and then open PR with that.

**Comment by anandwana001** [comment]
I made a new PR #1026  for this, sorry for the conflicting files.

**Pull request closed without merging**
