### PR TITLE
Make release 13

### PR DESCRIPTION
**Pull request by batbrain7**
Make release version 13,

Only to be merged after testing the release version locally

### CODE REVIEW

**Comment by batbrain7** [comment]
@arundhati24 I have tested the release version please check and confirm so that this can be merged

**Comment by batbrain7** [comment]
@arundhati24 did you test this ?

**Comment by arundhati24** [comment]
@batbrain7 As discussed in the meeting, I need to make some UI changes. I am working on them. Also, could you please look into the agenda doc and add the status of your work there? This time we need to test the release apk properly, so as to have a stable release. I will approve this PR once I make the requested changes and test the release apk.

**Comment by batbrain7** [comment]
@arundhati24 is this PR good to go ? I have tested it

**Comment by arundhati24** [comment]
@batbrain7 
Yes sure, I am testing the release apk and would ask a few other people also to test. If possible could you also please ask a few other people to test the release apk? We need to have a stable release this time.

**Comment by arundhati24** [comment]
@batbrain7 Should this be merged now?

**Comment by batbrain7** [comment]
Sure @arundhati24 this can be merged

**Comment by batbrain7** [comment]
@iamareebjamal please merge this

**Pull request merged**
