### PR TITLE
Added Sharing floating button

### LINKED ISSUE #1101: Adding a Share floating button
In the skills activity there is a need of sharing floating button so that the users can have the feature to share this app .This feature is very useful for sharing of app across social networks

screenshot_2018-01-25-17-41-06-198_ai susi

### PR DESCRIPTION
**Pull request by Ananthusubramanian**
Fixes #1101 
Changes:Created a sharing button for users to hare this app details across social network

Screenshots for the change: 
screenshot_2018-01-25-17-41-06-198_ai susi

### CODE REVIEW

**Comment by Ananthusubramanian** [comment]
Can anyone review this PR

**Comment by arundhati24** [comment]
@Ananthusubramanian I think this feature is not needed as the app already has it. Please check the Share SUSI option in Settings menu. You would find it there. :)

**Comment by arundhati24** [comment]
@chiragw15 What do you suggest? :)

**Comment by sauravvishal8797** [comment]
@Ananthusubramanian  I guess @arundhati24 is right, since the app share feature is already present in the settings menu it is not required here.

**Comment by chiragw15** [comment]
Sharing options already exists in settings. No need for it. Thus closing.

**Pull request closed without merging**
