### PR TITLE
Repaired the reappearing of toast message after every letter pressed.

### LINKED ISSUE #1903: toast message appears after every pressing every letter in skills activity
**Describe the bug**

Toast message appears multiple times after every letter is pressed in skills activity.

**Expected Behaviour**

It should not appear multiple times

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by Bhavnaharitsa**
Fixes #1903
Changes: The toast does not appear after every letter pressed

### CODE REVIEW

**Comment by iamareebjamal** [comment]
How does this solve the issue?

**Comment by Bhavnaharitsa** [comment]
@iamareebjamal Since,I'm trying to trying to show the toast message after search has been completed, try to perform search first and store the returned skill (boolean type) in skillfound, then use conditional statement to check if any skill was returned and also specify necessary actions.

**Comment by iamareebjamal** [comment]
First, search was performed after the check of some length, now it is performed unconditionally

**Comment by Bhavnaharitsa** [comment]
@iamareebjamal  Should I add a button to make the toast appear only after button clicked or perform a callback method ... the pseudo code looks somewhat like this 

private void performSearch(String currentText){
  Http.get(currentText,new Callback(){

     onSuccess(){
      if(no result){
     Toast.makeText(baseContext, R.string.skill_not_found, Toast.LENGTH_SHORT).show()
     }
    }

})
}

Thank you.

**Comment by Bhavnaharitsa** [comment]
@iamareebjamal Please opine on this context

**Comment by iamareebjamal** [comment]
I reacted +1 on your comment. Approval doesn't mean I need to write a comment

**Comment by Bhavnaharitsa** [comment]
Got it ! :)

**Comment by atm1504** [comment]
@batbrain7 @arundhati24 please close this issue. It has already been solved

**Pull request closed without merging**
