### PR TITLE
Fix : Added margin to the websearch.

### PR DESCRIPTION
**Pull request by mayank408**
Fixes issue #760 

Right margin is added to the websearch.
Screenshots for the change:

screenshot_1498125142

### CODE REVIEW

**Comment by mayank408** [comment]
@amitiwary999 Yes it was intentional like the left and right margin will have same width while the gap between the cards will be double of it. In this way it is uniform.

**Comment by amitiwary999** [comment]
Margin should be uniform everywhere like in allo app.

**Comment by amitiwary999** [comment]
@mayank408 I think this issue is related to both rss and websearch action type.

**Comment by mayank408** [comment]
@amitiwary999 As suggested by you I have made margin equal.

screenshot_1498141224

**Comment by mayank408** [comment]
@chiragw15 @amitiwary999 @the-dagger Pls review.

**Pull request merged**
