### PR TITLE
feat: Added profile page

### LINKED ISSUE #2101: Create Profile page
**Describe the feature you'd like**
Create a profile section in settings page. Clicking on this will open Profile fragment.
The page will have datas like:
* Email ID
* Name to be added by user
* Photo of the user: To be added by the user
* Option to Logout
* Display at the bottom of the page showing "I <name> accept the terms and conditions that susi posses"

**Use of this page**
* Use the name that user enters to make susi welcome user by that name. It is similar to that of Cortana and Siri.
* Feature request to susi server:
** Take the user name from profile page and add it in the server.

**Additional context**
This will make susi more appropriate to be as a personal assistant of the user. It will be very helpful for siri to communicate with the user. Use of this feature can be further extended when we successfully train hot-word detection. 

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by atm1504**
Fixes #2101 

Changes:
* Added profile activity with bottom navigation
* Added profile page
* Added profile edit page

Screenshots for the change: 
profile

### CODE REVIEW

**Comment by atm1504** [comment]
To be implemented in server with the help of peers.

**Comment by atm1504** [comment]
@iamareebjamal please review it.

**Comment by iamareebjamal** [comment]
No use unless implemented on server

**Comment by atm1504** [comment]
@iamareebjamal sir, I think we can keep it for now, and start implementing in server. And then finally make a bit change in it, so that it gets implemented.

**Comment by atm1504** [comment]
@batbrain7 sir I have created the issue in the susi server. I would be working on that issue very soon. And would use it in this pr.

**Comment by atm1504** [comment]
@batbrain7 @iamareebjamal as per the information from the peers, addition of username and profile picture is already implemented in the server. We need to make use of it.

**Comment by mariobehling** [comment]
This needs to be implemented on server.

**Pull request closed without merging**
