### PR TITLE
fix: Correct the spelling of dimension in comment

### LINKED ISSUE #1950: Use correct spell for dimension
**Describe the bug**

Error in the spelling of dimensions.

**Expected Behaviour**

**Steps to reproduce it**

**LogCat for the issue**

**Screenshots of the issue**

**Smartphone Info:**

|               | |
|---------------|-|
|Device         ||
|Android Version|    |

**Would you like to work on the issue?**
yes

### PR DESCRIPTION
**Pull request by chanmol1999**
Fixes #1950 Use correct spell for dimension
Changes: updated the spell 
Screenshots for the change:

### CODE REVIEW

**Comment by iamareebjamal** [comment]
This is not a variable name

**Comment by iamareebjamal** [comment]
The spelling of misspelled is also misspelled

**Comment by iamareebjamal** [comment]
> Use correct spell for dimension

Please forgive me for my humour but "Wingardium Leviosa"

**Comment by chanmol1999** [comment]
Please merge this @iamareebjamal

**Pull request merged**
