### PR TITLE
feat : store user settings on server

### PR DESCRIPTION
**Pull request by amitiwary999**
Fixes issue #766

### CODE REVIEW

**Comment by mayank408** [comment]
@amitiwary999 I think its too early to implement this. Its needs to be discussed what settings and preferences needs to be stored in the server. And these must be similar in all the clients. Also you have assigned the issue neither commented that you are working on it, so that we could first discuss how we going to approach this. 
@chiragw15 What do you think..?

**Comment by chiragw15** [comment]
@mayank408 I had a talk with @uday96 . He is also working on the same thing on web client. So, it is not a problem implementing it right now.

So, the settings for now can be : 
1. "enter_send"  :    value can be true/false    :    Will be used for inputing multi line queries. True means pressing enter will send message. False means pressing enter adds a new line.
2. "speech_output"   :    value can be true/false   :    Will be used for enable speech output when input type is speech.
3. "speech_always"   :    value can be true/false    :    Will be used to enable speech output irrespective input type.
4. "mic_input"        :        value can be true/false    :    Will be used to enable speech input.
5.  "theme"            :        value will be string (dark or light).     Will be used to change theme of user. 

Usage will be to get them from server during login. And saving them to server during log out.
@uday96 @chashmeetsingh views on this?

**Comment by chashmeetsingh** [comment]
Yes 👍🏻 I guess the colour scheme can also be stored on server for the themes, what do you think?

**Comment by uday96** [comment]
These key value pairs seem good to store user settings on server. :+1: 
For theme , in webchat its 'light' or 'dark' as of now. We can use colour schemes too, but  for that we will have to first figure out the components and have an object with the components as keys and colours as values. But 'light' or 'dark' should be fine for now I guess. We can later change it into colour schemes if required (Like if we are giving an option for custom themes too - Mario told that it isn't a priority as of now).

**Comment by amitiwary999** [comment]
Yes currently theme is not implemented in android. once it is implemented I will include it to store on server.

**Comment by chiragw15** [comment]
@amitiwary999 You need to make some changes. First you have to fetch user settings after login before starting main activity. Implement it in a way to fetch user settings at the time of login.
If( login == success) fetch user settings and start main activity. Secondly, only send settings to server when user change it and not when it is changed automatically due to absence of STT. Got my point?

**Comment by chiragw15** [comment]
@uday96 @chashmeetsingh right now, lets only keep theme as dark/light. We can add customizing of theme later on.

**Comment by chashmeetsingh** [comment]
Yup 👍

**Comment by amitiwary999** [comment]
@chiragw15 what do you mean by setting changes automatically? You mean STT setting changes automatically according to device so not send it to server when it changes automatically?

**Comment by amitiwary999** [comment]
@chiragw15 @mayank408 review

**Comment by chiragw15** [comment]
@amitiwary999 Yes. When user change setting himself, then only send it to server. Also, do this in background so user doesn't have to wait. Send mic and theme settings too. Just make the changes and after PR for theme settings gets merged, we can merge this.

**Comment by amitiwary999** [comment]
@chiragw15 @mayank408 review

**Comment by amitiwary999** [comment]
will reopen this pr and start working on it when issue [828](https://github.com/fossasia/susi_android/issues/828) is solved otherwise it will create large conflicting files.

**Pull request closed without merging**
