### PR TITLE
Fix : update rss action type

### PR DESCRIPTION
**Pull request by amitiwary999**
Fixes issue #809

### CODE REVIEW

**Comment by amitiwary999** [comment]
@chiragw15 @mayank408 review.

**Comment by chiragw15** [comment]
@amitiwary999 Please post a screenshot of how it looks now.

**Comment by amitiwary999** [comment]
@chiragw15 

screenshot_2017-07-11-04-14-09

**Comment by chiragw15** [comment]
@amitiwary999 Where is the image mentioned in this PR. https://github.com/fossasia/susi_server/pull/337 . The point was to display the rss similar to how we show websearch. @dynamitechetan According to above PR, there should be image links too in the server response. I am not able to find them in any rss response. Can you check it please?

**Comment by amitiwary999** [comment]
@chiragw15 there is no link for image in susi reply.

**Comment by amitiwary999** [comment]
@chiragw15 should I reopen the pr #772 because rss action type is not updated properly in server. I am trying to solve it but not able to import susi_server code in eclipse. There is some problem in susi_server code.

**Comment by chiragw15** [comment]
@amitiwary999 It would be better if this is actually done on the server. It will reduce around 200 lines of code plus a memory leak as well. Just try solving it once. If it's not possible to solve this on the server, then reopen the PR.

**Comment by chiragw15** [comment]
Closing this for now. Reopen it when server response is fixed.

**Pull request closed without merging**
