### PR TITLE
Fixes #118 Bug: in new Wallpaper feature

### LINKED ISSUE #118: Bug: in new Wallpaper feature
Selecting an image from Gallery is not setting it as chat background.
I get a toast saying "Editing is not supported for this image"

Steps:
1. open top right menu.
2. select wallpaper
3. select gallery
4. choose any image
5. toast appears with no change in background

### PR DESCRIPTION
**Pull request by rahulworld**
Fixes issue #118

Changes: When device is not support editing then image select automatically set as a chat background.

Screenshots for the change:

### CODE REVIEW

**Comment by gogeta95** [comment]
@rahulworld could you also make the crop box 16:9 is same PR? No device is square. image

**Comment by rahulworld** [comment]
@gogeta95  okk

**Comment by rahulworld** [comment]
@gogeta95  i make crop 16:9  box but this pull request merged.

**Comment by gogeta95** [comment]
You can always send a new PR :)

**Pull request merged**
