### PR TITLE
Fixes #1149 -Added confirmation before exit on the login screen

### LINKED ISSUE #1149: Add an Alert dialog to confirm before closing the app when (logging in) in the app.
**Actual Behavior**

On exiting the application at the time of login, the application get close directly , may be user don't want to close it & mistakenly it get closed. 

**Expected Behavior**

A popup must appear that confirms user ,that he/she really wants to close the application or not.

**Step to reproduce**

1. Reinstall or clear the data of the app.
2. Launch the app.
3. Press the back button when the login screen appear.

**Would you like to work on the issue**?

Yes.

### PR DESCRIPTION
**Pull request by ujjwalagr**
**Fixes** #1149 -Added confirmation before exit.

**Changes:**
 1. Updated LoginActivity.kt  overriding the back button pressed function and added confirmation before exit when user is (logging in) in the app.
 2. Added Toast that confirm the exit status at the login activity

### CODE REVIEW

**Comment by ujjwalagr** [comment]
@chiragw15 please review.

**Comment by arundhati24** [comment]
@ujjwalagr 
As you have not added the screenshot for the change, as far as I understand, you want to prompt the user if the user happens to press the back button that will cause her/him to exit from the app. If that is true, I would like to point out that the app already prompts the user for the same by displaying a toast that asks the user to press the back button twice in case s/he wants to exit from the app. So, I guess this extra confirmation is not required.

**Comment by ujjwalagr** [comment]
@arundhati24 I already mentioned that user is not getting any confirmation on the login screen, yeah you are right that afterwards on the Chat screen user gets a toast but I found the issue on the login screen(LoginActivity.kt).

**Comment by arundhati24** [comment]
@ujjwalagr  Actually issue #1080  addresses a similar issue but when the user accesses the login screen from the settings. So, I suggest you to make the title of the issue a bit clearer. Also, it would be better if you could add a little clearer description regarding the change you made.

**Comment by ujjwalagr** [comment]
Previously
whatsapp-video-2018-03-02-at-10 01 57-pm

After updation
whatsapp-video-2018-03-02-at-9 57 30-pm

**Comment by ujjwalagr** [comment]
@arundhati24 Please review.

**Comment by arundhati24** [comment]
@ujjwalagr I would suggest you to keep the toast message same as that used in the main app.

**Comment by ujjwalagr** [comment]
@arundhati24 Okay ,So do i have to send the pr again?

**Comment by arundhati24** [comment]
@ujjwalagr No. You can make the required changes and then you can squash those commits into one.

**Comment by ujjwalagr** [comment]
@arundhati24 Squashing would going to be complicated rather I close this request And create a new PR simply.Is it okay?

**Pull request closed without merging**
