### PR TITLE
Fixed Issue:

### LINKED ISSUE #961: App crashes on searching any website. example: hello.com
**Actual Behaviour**

App crashes and doesn't start again when any website name is searched. Example hello.com

**Expected Behaviour**

Gives any information about the website or link to the website.

**Steps to reproduce it**

Just type any website.

**LogCat for the issue**

09-23 15:06:21.681 20093-20093/org.fossasia.susi.ai I/cr_BrowserStartup: Initializing chromium process, singleProcess=true
09-23 15:06:21.939 20093-20093/org.fossasia.susi.ai D/AndroidRuntime: Shutting down VM
09-23 15:06:21.940 20093-20093/org.fossasia.susi.ai E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: org.fossasia.susi.ai, PID: 20093
                                                                      java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
                                                                          at org.fossasia.susi.ai.chat.adapters.viewholders.LinkPreviewViewHolder.setView(LinkPreviewViewHolder.java:116)
                                                                          at org.fossasia.susi.ai.chat.adapters.recycleradapters.ChatFeedRecyclerAdapter.onBindViewHolder(ChatFeedRecyclerAdapter.java:277)
                                                                          at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6279)
                                                                          at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6312)
                                                                          at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5258)
                                                                          at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5521)
                                                                          at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5363)
                                                                          at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5359)
                                                                          at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2141)
                                                                          at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1525)
                                                                          at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1488)
                                                                          at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:570)
                                                                          at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3506)
                                                                          at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3254)
                                                                          at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1593)
                                                                          at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4625)
                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:873)
                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:685)
                                                                          at android.view.Choreographer.doFrame(Choreographer.java:618)
                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:859)
                                                                          at android.os.Handler.handleCallback(Handler.java:751)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6195)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:874)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764)
09-23 15:06:21.943 20093-20093/org.fossasia.susi.ai E/MQSEventManagerDelegate: failed to get MQSService.
09-23 15:06:21.971 20093-20093/org.fossasia.susi.ai I/Process: Sending signal. PID: 20093 SIG: 9

**Screenshots of the issue**

Where-ever possible add a screenshot of the issue.

**Would you like to work on the issue?**

I would like to work on this issue.

### PR DESCRIPTION
**Pull request by yashLadha**
* Crashing of app on input of a webpage

Fixes #961 

screenshot_1507524457
screenshot_1507524660

### CODE REVIEW

**Comment by collinx** [comment]
@yashLadha Is crashing stopped or not?? App is still crashing on my side.

**Comment by yashLadha** [comment]
App has stopped crashing. Because it is looking for the tag of skills when a website has given as input. But i still have to figure out the layout which is inflating. It is currently inflating chatViewHolder with default content. @collinx

**Comment by yashLadha** [comment]
@collinx @chiragw15 Please review it has stopped crashing.

**Comment by yashLadha** [comment]
@collinx I have implemented changes on the inflation as well.

**Pull request merged**
