### PR TITLE
Ordered feedback

### LINKED ISSUE #2023: Feedback should be ordered by newest on top
**Describe the bug**
Currently when user gives a feedback on a skill its displayed at last in reviews .

**Expected Behaviour**
Instead feedback must be displayed in order such that newest one is on the  top inspite of the oldest on top such that user can also instantly see his feedback.

**Steps to reproduce it**
change in feedback activity 

**LogCat for the issue**

**Screenshots of the issue**

gifreview

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Vivo Y83|
|Android Version  |8.1.0 |

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by Bhavnaharitsa**
Fixes #2023 

Changes:Made changes in FeedbackActivity by correcting the reverse layout from false to true. Converting reverse layout to true will display the layout from end to start which means the recently added feedbacks will display on top.

### CODE REVIEW

**Comment by immadisairaj** [comment]
@Bhavnaharitsa please follow semantic guidelines

**Comment by Bhavnaharitsa** [comment]
@iamareebjamal @batbrain7 Please review sir !!

**Comment by Bhavnaharitsa** [comment]
@iamareebjamal please review !!!

**Comment by arundhati24** [comment]
Check out the cooking guide skill as an example of why it won't work.

**Comment by Bhavnaharitsa** [comment]
@arundhati24 I think the issue itself is misunderstood.  After reading the explanation I understood what had to be done. I worked as per the description in #2023 . Now that it's understood,I would like take upon the revised issue.

**Pull request closed without merging**
