### PR TITLE
issue-Soft keyboard get open automatically solved

### PR DESCRIPTION
**Pull request by vikiCoder**
Now, whenever the app will open, the soft keyboard will open automatically and the focus will be on messagebox.

### CODE REVIEW

**Comment by daminisatya** [comment]
@vikiCoder Please squash your commits and give a meaningful commit message. ```done nothing``` doesn't give me an idea of what you have done :)

**Comment by daminisatya** [comment]
Also please resolve the merge conflict! Thank you.

**Comment by daminisatya** [comment]
@vikiCoder Which issue are you solving? please follow the pattern in the commit message. 
```Fixes #<issue number> : some meaningful commit message depicting your chanegs``` This way we can auto close the associated issue.

**Comment by addiittya2006** [comment]
gradle.xml & chat-message-view.iml must not be changed for this.
Do a reset, then checkout the extra files from the previous commit to resolve merge conflicts.
And, update the commit message.

**Pull request closed without merging**
