### PR TITLE
Fix: wrong link in about_us fragment

### LINKED ISSUE #971: Wrong link in About Us Page
**Actual Behaviour**

The Link opens the stackOverflow website.

**Expected Behaviour**

The link should open SUSI.AI

**Steps to reproduce it**

Open the About Us Page and click on SUSI AI 

**Screenshots of the issue**

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by Arshilgenius**
Fixes #971 

Earlier due to clickable attribute it was redirecting to stackoverflow post.

### CODE REVIEW

**Comment by chiragw15** [comment]
Please link it to susi.ai

**Comment by Arshilgenius** [comment]
Sure

**Comment by chiragw15** [comment]
@Arshilgenius please follow commit style guidelines https://github.com/fossasia/susi_android/blob/development/docs/commitStyle.md . Use git amend to change commit message please.

**Comment by chiragw15** [comment]
@Arshilgenius commit message. Not the title of the PR.

**Comment by Arshilgenius** [comment]
@chiragw15  please review

**Pull request merged**
