### PR TITLE
Fixes #464 : Now alarm can be set from the app itself.

### LINKED ISSUE #464: Adding setting alarm feature in the app itself
**Actual Behaviour**

We can't set the alarm on our mobile through susi app.

**Expected Behaviour**

To make the app much more intitutive , we must add this feature just like google allo.

**Would you like to work on the issue?**

Yes , I am already working on it.

### PR DESCRIPTION
**Pull request by mayank408**
Fixes issue #464

Screenshots for the change: 

screenshot_1484328654
screenshot_1484328645
screenshot_1484328830
screenshot_1484328818

### CODE REVIEW

**Comment by jig08** [comment]
* Would it cover cases of a 24hour clock ?
* It works fine with queries like `Set Alarm for 2:30 AM` ?
* It'll be nice if in the above case it returns `Setting alarm for 2:30 AM`

Just a couple of questions. Thanks !

**Comment by mayank408** [comment]
@jig08 
* No it doesn't cover 24 hours cases instead you have to use either AM or PM .
* Yup it works fine for queries like Set Alarm for 2:30 AM


screenshot_1484331452

screenshot_1484331260

* It also shows the toast for the time remaining for the alarm

**Comment by mayank408** [comment]
@jig08 @daminisatya @the-dagger Kindly review this...

**Comment by mananwason** [comment]
This looks good to be merged!

**Pull request merged**
