### PR TITLE
Fixes #125: Date stamp updated

### LINKED ISSUE #125: Issue with the time stamp
I think there is some issue with time stamp of messages . See the screenshot.

whatsapp image 2016-10-10 at 12 14 38 pm

### PR DESCRIPTION
**Pull request by mayank408**

### CODE REVIEW

**Comment by the-dagger** [comment]
@mayank408 Is the date getting updated on scroll?

**Comment by mayank408** [comment]
@the dagger I tried to implement it but the app starts crashing thats why I revert the changes . I want to merge this pull request after which I will open a new issue for implementing. that. For now it only shows the current date only.

**Comment by mayank408** [comment]
@jig08 @daminisatya Pls merge it so that I can open a new issue regarding this.

**Comment by mariobehling** [comment]
Thank you. Keep it up!

**Pull request merged**
