### PR TITLE
feat: Filter skills according to the user choice

### LINKED ISSUE #1458: The user cannot choose the order in which the skills are shown
**Actual Behaviour**

Currently, the skills are seen in the descending order of top rated skills.

**Expected Behaviour**

Allow the user to choose the order in which s/he wants to see skills.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by atm1504**
Fixes #1458

Changes:
* Made the basic setup ready
* Implemented filter functionalities

Screenshots for the change: 
ezgif com-video-to-gif

APK: 
[app-fdroid-debug.apk.zip](https://github.com/fossasia/susi_android/files/3413805/app-fdroid-debug.apk.zip)

### CODE REVIEW

**Comment by atm1504** [comment]
@liveHarshit @batbrain7 @arundhati24 @iamareebjamal please review it.

**Comment by atm1504** [comment]
> Shimmer should not overlap.

U mean that the data present below the shimmer should not be shown?

**Comment by liveHarshit** [comment]
> > Shimmer should not overlap.
> 
> U mean that the data present below the shimmer should not be shown?

During shimmer, data should not display.

**Comment by atm1504** [comment]
@liveHarshit updated it. Please review it.

**Comment by liveHarshit** [comment]
> @liveHarshit updated it. Please review it.

Please update the GIF.

**Comment by atm1504** [comment]
ezgif com-video-to-gif

@liveHarshit updated. Please review

**Pull request merged**
