### PR TITLE
Make release 12

### PR DESCRIPTION
**Pull request by batbrain7**
To be merged after testing

### CODE REVIEW

**Comment by batbrain7** [comment]
@arundhati24 please list the changes done by you so that a message for the mailing list can be prepared

**Comment by arundhati24** [comment]
@batbrain7 I have prepared a draft for it already and have posted it on Gitter channel. It would be great if we could have #1550 and #1563 merged. I would immediately post an APK on the SUSI.AI mailing list once these are merged because then we would have this new UI flow to add for the new version. We will have to test it properly as well.
We can release without these PRs as well but then the skills won't load if a user has not set a language explicitly from the settings at least once. Also, s/he won't be able to load skill details on clicking a skill card on group wise skills fragment. Hence, it would be great if we could have them merged.

**Comment by iamareebjamal** [comment]
@batbrain7 Increment versionCode and name, this should be the first task to do after merging in master

**Comment by iamareebjamal** [comment]
Tests are failing @arundhati24 @batbrain7

**Comment by iamareebjamal** [comment]
@batbrain7 @arundhati24 Please merge this soon and tag the branch with `v{versionName}` syntax so F-Droid build can be released

**Comment by batbrain7** [comment]
@iamareebjamal please merge this

**Comment by batbrain7** [comment]
@iamareebjamal please merge this

**Pull request merged**
