### PR TITLE
chore: Merge dev to master v1.0.6

### LINKED ISSUE #1277: Merge dev to master
Merge dev to master for version v1.0.6

### PR DESCRIPTION
**Pull request by iamareebjamal**
Fixes #1277

### CODE REVIEW

**Comment by batbrain7** [comment]
@iamareebjamal can you please tell why is this PR needed?

**Comment by iamareebjamal** [comment]
To merge dev and master

**Comment by iamareebjamal** [comment]
Please check that app is not crashing for any instance and we'll merge it

**Comment by iamareebjamal** [comment]
@batbrain7 When merging PRs, use squash and merge please to prevent redundant commit messages

**Pull request merged**
