### PR TITLE
feat : adding hotward detection using snowboy

### PR DESCRIPTION
**Pull request by chiragw15**
Fixes issue #648 

Changes: Hotword detection added using snowboy.

### CODE REVIEW

**Comment by chiragw15** [comment]
@mayank408 @amitiwary999 @betterclever review please.

**Comment by chiragw15** [comment]
@mayank408 can you also test this once and see if you face the same issue?

**Comment by mayank408** [comment]
@chiragw15 I tested the app with varying sensitivity. The hotword is recognized only a single time with sensitivity .53. When it is set higher it starts recognizing the hotword even when there is no voice and with low sensitivity it does not recognize at all.

**Comment by chiragw15** [comment]
@betterclever @mayank408 @amitiwary999 @chashmeetsingh please review. For now I have kept sensitivity at 0.5 and audio gain at 0. Will later on add an option in settings to change it. Plus hotword detection will also improve when more number of people will train susi hotword with their voice on snowboy website.

**Comment by betterclever** [comment]
@chiragw15 Can you refactor the Snowboy Wrapper code to follow same code style as rest of the app and also Java standard? Codacy also reported the issues. It is better to have a consistent code style.

**Comment by chiragw15** [comment]
@betterclever Done :+1:

**Comment by chiragw15** [comment]
APK for testing : https://drive.google.com/file/d/0B6IO4qTKhVUCcEt4RjhjWjVTa00/view?usp=sharing

**Comment by betterclever** [comment]
@chiragw15 I tested app. Hotword working pretty well.

**Comment by chiragw15** [comment]
See, for every user sensitivity should not be different. There are varied results now because the hotword is not much trained on the snowboy website. I see only 10 people have contributed to the training by their voice. https://snowboy.kitt.ai/hotword/7915 . When this number goes to like 50, the results will improve drastically and hotword detection will be near perfect. Till then I was planning to introduce a change sensitivity option in settings for testing purposes. When the model is trained more, we can remove it and fix the sensitivity which gives best results.

**Comment by mayank408** [comment]
@chiragw15 I have tested your app on 3 different phones which are MI Redmi, Honor 5X and moto G3.
The hotword recognized in moto g3 for 2 times out of 10 or 15 while it keeps on detecting even when there is not a single sound in the other two mobile phones. 
I think every mobile works on different sensitivity and when we are targeting a large audience we must ensure that it works in all the mobile phones. 
The point of training the model is right as you said but still I am thinking how can we find the right value of sensitivity in each of the phone.

**Comment by chashmeetsingh** [comment]
I don't think so sensitivity has to do something with the devices. If you check the FAQs page, you will find out that we need to play with the sensitivity a little for best results. http://docs.kitt.ai/snowboy/#what-is-detection-sensitivity

**Comment by mayank408** [comment]
@chashmeetsingh Then what do you think is the factor that is causing different results.?

**Comment by chashmeetsingh** [comment]
Read the FAQ: `Detection sensitivity controls how sensitive the detection is. It is a value between 0 and 1. Increasing the sensitivity value lead to better detection rate, but also higher false alarm rate. It is an important parameter that you should play within your actual application.`

**Comment by chiragw15** [comment]
@chashmeetsingh It is used to play a ding sound on hotword detection. We don't need it. Removing it.

**Comment by chashmeetsingh** [comment]
Also, I guess we should add an option in settings to enable/disable hot word right?

**Comment by chiragw15** [comment]
@mayank408 @amitiwary999 @chashmeetsingh @betterclever I found the problem. Sensitivity has not much to do with hotword detection. Once the model is trained, hotword detection will be perfect. I am using my personal model (susi.pmdl) right now for hotword detection so it works great for me and people with similar voice like me but not for everyone. So once the training is complete we'll get a universal model for everyone (susi.umdl). See this link http://docs.kitt.ai/snowboy/#my-pmdl-model-works-well-for-me-but-does-not-work-well-for-others 
it says 
```
My pmdl model works well for me, but does not work well for others

Models with suffix pmdl are personal models thus they are supposed to only work well for the person who provides the audio samples. If you are looking for a model that works well for everyone, you should use the universal model (with suffix umdl).
``` 
So, we will need to customize hotword detection for every user by making them say susi 3 times at the first run after installation. See this link http://docs.kitt.ai/snowboy/#api-v1-train 
it says 
```
You can define truly customized hotword for each of your end customer. Just ask them to say the hotword 3 times and a model will be trained on the fly!

    Endpoint: https://snowboy.kitt.ai/api/v1/train/
    Type: POST
    Return: a binary personal model (.pmdl), or error
```

**Comment by chiragw15** [comment]
@chashmeetsingh removed `ding.wav` .

**Comment by chashmeetsingh** [comment]
The alexa.pmdl file still remains

**Comment by chiragw15** [comment]
@mariobehling @the-dagger @mayank408 @betterclever @amitiwary999 @chashmeetsingh 
The hotword detection is implemented. 

Problem for now : 
The hotword detection uses a model file from snowboy website. This model file is of 2 types : `susi.pmdl` and `susi.umdl`. pmdl stands for personal model and umdl stands for universal model. The process of getting a personal model file (.pmdl) is simple. Just say susi thrice on snowboy website and download the personal model and use it. But the problem with personal model is that it is defined for a specific person. I am using my personal model (susi.pmdl) right now for hotword detection so it works great for me and people with similar voice like me but not for everyone. And to get a universal model file (.umdl), we need minimum 500 person to train the susi hotword on snowboy website by saying 'susi' thrice. Once we have a universal model file, the hotword will work great for everyone. But it may take time since right now I see only 10 people trained the model and we want 490 more. 
Alternate for this now : 
Snowboy provides an api to train and get a pmdl file. As mentioned in above comment, according to snowboy docs
```
You can define truly customized hotword for each of your end customer. Just ask them to say the hotword 3 times and a model will be trained on the fly!

    Endpoint: https://snowboy.kitt.ai/api/v1/train/
    Type: POST
    Return: a binary personal model (.pmdl), or error
```
We can generate a pmdl model for everyone by asking them say 'susi' thrice after installation of app. By this way everyone will use their personal model and hotword detection will work for them smoothly. Once we have universal model trained by 500 person, we can update the app and use universal model which will work for everyone and there won't be a need for every new user to train model with his/her voice. 

Views on this?
We have three ways now : 
1. Train the model for everyone by making them say susi thrice and use it. If this sounds fine, I'll create a new issue for it and work.
2. Wait for 500 people to train the model and get universal model and use it.
3. Use some other alternative for snowboy.

**Comment by chashmeetsingh** [comment]
Are you trying to say we can include the training API for creating a .pmdl file within the app?

**Comment by chiragw15** [comment]
@chashmeetsingh thats a universal model file I have kept deliberately to test the hotword detection with a universal model. I have commented it. If someone wants to test hotword detectection with universal model file of alexa, just uncomment [this](https://github.com/fossasia/susi_android/pull/710/files#diff-22bff6b017cf1951fbeead95da029dd9R8) and [this](https://github.com/fossasia/susi_android/pull/710/files#diff-ef18f4a81c47a4d4cb2d031f483895b2R23) and use. The hotword will be "alexa".

**Comment by chiragw15** [comment]
@chashmeetsingh yes

**Comment by amitiwary999** [comment]
@chiragw15 it means when user install app he/she can train model and use hotword. So .pmdl will generate after that?

**Comment by chiragw15** [comment]
@amitiwary999 When the user will run the app after installation, he will be prompted to say susi thrice. These three recordings will then be sent to this http://docs.kitt.ai/snowboy/#api-v1-train API as a post parameter. The API will return a .pmdl file which then will be used for hotword detection.

**Comment by chashmeetsingh** [comment]
What about creating a simple web app which does that instead of adding it to the app and later removing this functionality after a universal model has been obtained?

**Comment by chiragw15** [comment]
What? NO. You are not getting the flow. We have to use the restful API of snowboy which takes 3 recordings as parameters and returns a .pmdl file when API is called. And this .pmdl file then should be stored in assets folder in app from where it is copied to mobile storage and then used for hotword detection. How creating a webpage would help in that? @chashmeetsingh 
The flow will be : 
1. The app started after installation.
2. User prompted to a screen where he/she is asked to speak susi thrice.
3. These three recordings are then stored. (.wav files)
4. Now  http://docs.kitt.ai/snowboy/#api-v1-train this API is called passing these 3 recordings and.
5. The above API will return .pmdl file.
6. Store this .pmdl file in mobile storage in snowboy folder.
7. Use it for hotword detection.

I don't know if making a web app will help in this.

**Comment by chashmeetsingh** [comment]
I don't think so it would be a good idea to ask user to train a hot word in the app. This feature would be removed in future eventually so I don't think so it's good to add it in the app.

The website thing I was talking about was a place where one does not need to login/signup just give 3 inputs that's all.

**Comment by chiragw15** [comment]
Google also follow similar approach to train the language model. This will be optional. If user wants to train then he can else can leave it too. Or else we can wait for 490 more person to train susi hotword on snowboy webite and use general model. @Orbiter @mariobehling @the-dagger  
screenshot_20170701-212215 1

screenshot_20170701-212241

**Comment by the-dagger** [comment]
Sounds good @chiragw15. 👍
It it's working well after testing then I think we can merge this.

**Comment by chiragw15** [comment]
@the-dagger Yes, I have tested it a lot and it works great for me. Check out this video (https://youtu.be/V9N6K4SzpXw ) . I'll just resolve conflicts and this can be merged. After that I'll create sub issues and implement the above mentioned strategy.

**Comment by chiragw15** [comment]
@the-dagger please review and merge this.

**Pull request merged**
