### PR TITLE
Fixes issue:#136 Removed splash screen functionality

### PR DESCRIPTION
**Pull request by nikimullick**

### CODE REVIEW

**Comment by jig08** [comment]
@nikimullick 
- Squash your commits for one commit per Issue/PR.
- Follow naming guidelines as mentioned in README.

**Comment by nikimullick** [comment]
@jig08 Do I now need to make a new PR after squashing?

**Comment by jig08** [comment]
Nope, in the same branch itself.. squash these two commits.

**Comment by gogeta95** [comment]
@mariobehling @the-dagger  we might want to close this issue now, because i have implemented login/ sign up functionality. and app has to decide whether to send user to chat screen or login screen based on access token and its expiry, we can keep that logic in splash screen. thoughts?

**Comment by mariobehling** [comment]
No splash screen for the moment, please. Which issue are you talking about? This is a pull request here.

**Comment by nikimullick** [comment]
@jig08 could you guide me on squashing the commits i'm having a lot of trouble with this...?I tried doing but instead i 'm ending up making more commits :(

**Comment by daminisatya** [comment]
@nikimullick 

There are two ways in which you can squash.

While pushing another commit, you can amend to the previous commit. git commit --amend (when you already have a commit existing and you want to amend to it) instead of doing git commit -m "message" every time.

But then you dint follow the above amending rule, and you pushed multiple commits (like how you have done now) You can squash everything into one single commit. Check your git log and decide on till where you want to squash. suppose there are 2 commits of yours which you want to squash into single, then the command goes git rebase -i HEAD~2. Which leads to an editor where you will be asked for every commit whether you want to pick to squash. type squash for all the 2 commits present and exit. The rebase continues and you have force push the changes, as in git push -f origin <branch>.

This might be a bit confusing, but please watch this video

**Comment by daminisatya** [comment]
@nikimullick  please read my comments on this PR. I have already addressed on how one can handle merge conflicts and commit squashes. Please check out the video links too. They help a lot. Any further query please let us know. Thank you 
[Here is the link](https://github.com/fossasia/susi_android/pull/83)

**Comment by jig08** [comment]
@nikimullick 
@daminisatya has explained very much in detail, hope it resolves your query 😃

**Pull request closed without merging**
