### PR TITLE
fixes issue #108 improve search UI

### PR DESCRIPTION
**Pull request by amitiwary999**
fixes issue #108 Now if search text found then only text background colour will be change.

### CODE REVIEW

**Comment by jig08** [comment]
@amitiwary999 Always post before and after screenshots for easier PR review. Cheers !

**Comment by daminisatya** [comment]
@amitiwary999 thanks for the PR , but please update your commit to the required format. Please read the readme for more info. If you are still facing the problem you can ask anyone over here thank you

**Comment by jig08** [comment]
@amitiwary999 It shows two commits now, squash 'em !

**Comment by amitiwary999** [comment]
@jig08 these two commits are different both have different codes and last one is correct

**Comment by jig08** [comment]
@amitiwary999 Then kindly follow the pattern of one commit per issue/per PR.
Also TravisCI checks have failed, pls look into it as well.

**Pull request closed without merging**
