### PR TITLE
Add hindi localization

### LINKED ISSUE #1064: Add Hindi localization in the app
**Actual Behaviour**

No hindi localization.
Contain just Brazilian localization.

**Expected Behaviour**

Have Hindi localization too.

**Would you like to work on the issue?**

yes

### PR DESCRIPTION
**Pull request by DipanshKhandelwal**
Fixes #1064 

Changes:  
Add hindi localization.
Added values-hi/strings.xml

### CODE REVIEW

**Comment by abishekvashok** [comment]
@DipanshKhandelwal please update your fork.

**Comment by DipanshKhandelwal** [comment]
@abishekvashok thanks didn't saw those changes.

**Comment by abishekvashok** [comment]
@DipanshKhandelwal pls rebase and squash the commits.

**Comment by DipanshKhandelwal** [comment]
This branch now has its last commit.

**Comment by chiragw15** [comment]
Thanks @DipanshKhandelwal

**Pull request merged**
