### PR TITLE
Fixes #497 : Allowing user to send SMS through the app.

### LINKED ISSUE #497: Allow user send SMS through susi.
**Actual Behaviour**

User can't send SMS through the app.

**Expected Behaviour**

Just like allo , user must have the ability to send SMS through the aap.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by mayank408**
Fixes issue #497

Changes: User can send SMS through the app.

Screenshots for the change: 

screenshot_1485968788
screenshot_1485968807

### CODE REVIEW

**Comment by mayank408** [comment]
@jig08 @daminisatya @the-dagger  could you pls review this...

**Comment by mayank408** [comment]
@jig08 @daminisatya @the-dagger could you pls review this...

**Comment by the-dagger** [comment]
I think that this will work only if we type in english.
Which is not a good solution

**Comment by Abhi2424shek** [comment]
@mayank408 as far as I know sms has only english support natively, so can you implement the translate to english if they have entered a native language, the Google Translate API and it has an option only to specify the output language.

**Comment by Abhi2424shek** [comment]
@mayank408 don't make PRs for new commits just commit to this PR. :)

**Pull request closed without merging**
