### PR TITLE
fixes issue #267 simplify design of login/signup screen

### PR DESCRIPTION
**Pull request by amitiwary999**
fixes issue #267 simplify design of login/signup screen

### CODE REVIEW

**Comment by mariobehling** [comment]
@amitiwary999 Please solve failing test.

**Comment by amitiwary999** [comment]
@mariobehling I am not able to find why it failed?
@the-dagger can you please review this code?

**Comment by the-dagger** [comment]
@amitiwary999 The conectedTest failed for the build.
Seems like it is unable to run espresso tests on the modified Login screen.
Have a look at the circleCi logs and see if you are able to fix it.
https://circleci.com/gh/fossasia/susi_android/98#tests/containers/0

**Comment by amitiwary999** [comment]
@the-dagger I will try.

**Pull request closed without merging**
