### PR TITLE
Fixes #484: Using Cardviews instead of ChatMessageViews

### LINKED ISSUE #484: Using Cardviews instead of current ChatMessageViews
**Actual Behaviour**

Currently ChatMessageViews provided by ChatMessageView library are being used throughout the app.
This makes implementation of some other views difficult like after multiple websearch results, results displayed would look better in a scrollable view containing cards.

**Expected Behaviour**

I would highly suggest use of CardViews throughout the app since it makes it look modern, compact and helps making further views easy and uniform. 

**Screenshots of the Initial Card Implementation**

screenshot_1482062777

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by betterclever**
Fixes issue #484 : Using Cardviews instead of ChatMessageViews

Changes: Cardviews used for all the message view. Timestamps also made compact like whatsapp. They now move down or remain in single line depending on the size of message. 

Screenshots for the change: 

screenshot_1486087040

### CODE REVIEW

**Comment by mayank408** [comment]
@betterclever Just a suggestion if you could make the text colour inside card view more dark or black , and keep time textview light... it will look great and also it will distinguish between them . This way the we can keep the user's focus on message rather than time just like WhatsApp do. . Refer this screenshot.

unknown

**Comment by betterclever** [comment]
@mayank408 Good suggestion.

**Comment by betterclever** [comment]
screenshot_1486131567
@mayank408 Now?

**Comment by Abhi2424shek** [comment]
Can you also add a margin to the bottom of the moreshow found so that the design matches it.

**Comment by betterclever** [comment]
@Abhi2424shek It is already there. It is not visible in the current scrolled state of recyclerview as it hidden behind the sendMessageLayout. Notice the above screenshot for that.

**Comment by betterclever** [comment]
@the-dagger @jig08 Please have a look

**Comment by the-dagger** [comment]
@betterclever Looks good to me, but there seems to be some conflicts due to merges.
Resolve it and I'll merge this. :)

**Comment by betterclever** [comment]
@the-dagger Everything fixed. Please merge.

**Pull request merged**
