### PR TITLE
Changed app label from SUSI AI to SUSI.AI (Fixed #1502)

### LINKED ISSUE #1502: Incorrect app label
**Actual Behaviour**

Currently, the app label has been set as 'SUSI AI'.

**Expected Behaviour**

It should be 'SUSI.AI'

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by arundhati24**
Fixes #1502
Changes: Changed app label from SUSI AI to SUSI.AI.

### CODE REVIEW

**Comment by batbrain7** [comment]
@arundhati24 let's ask @mariobehling  first

**Comment by arundhati24** [comment]
@batbrain7 okay. Actually on Play Store it is SUSI.AI and everywhere else including the susi.ai website, it is SUSI.AI and not SUSI AI. Hence, I changed this.

**Comment by arundhati24** [comment]
@batbrain7 I don't think this is such a big issue. Please have a look at the README and also the logo that we use in our app. Also, the name on the app bar. Everywhere it is SUSI.AI. Just as it is not right to distort the logo of any organization or project, it is also not right to change the name of the app in different places. I think this should be corrected before next release.

**Comment by batbrain7** [comment]
also if you are changing strings then update all the strings in the app

**Pull request merged**
