### PR TITLE
Fixes #87: added chat background options

### LINKED ISSUE #87: chat background image
like whats app and hike messenger

### PR DESCRIPTION
**Pull request by rahulworld**
Chat Background image
there is three way for change chat background activity
go to menu then wallpare 
1. using gallery
2. No wallpaper
3. default

### CODE REVIEW

**Comment by jig08** [comment]
@rahulworld 
Resolve conflicts in this PR.

Also,
- Make sure there is one commit per issue/per PR
- Use the format , i.e. `Fixes #87: Added chat background options` for commit name in this case

**Comment by rahulworld** [comment]
@daminisatya  if any improvement please tell me about this issue

**Comment by jig08** [comment]
@rahulworld Use the format `Fixes #87: Added chat background options` for your commit name as well.

**Comment by daminisatya** [comment]
@rahulworld , code looks good but i want the commit in the required format as @jig08 said

**Comment by jig08** [comment]
@rahulworld It shows two commits now, squash 'em !

**Comment by rahulworld** [comment]
@daminisatya  i have done commit name that format and one commit.

**Pull request merged**
