### PR TITLE
fix: Search bar not closing on pressing android's back button

### LINKED ISSUE #2459: Search bar for skills does not close on going back with android nav button
The search bar for skills closes when we press the action bar back button or the "x" on the search bar. But it does not close when we press the android navigation back button.

**Expected Behaviour**

The search bar should behave the same as it does when the action bar back button is pressed.

**Steps to reproduce it**

1. Press the search button in the Skills page.
2. Repeatedly pressing the android back button does not cause anything. Ideally the search bar should close.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by shashwatjolly**
Fixes #2459 

Changes: 
Added a key listener on the EditText for search bar to detect a back press and act accordingly.

Before:
searchBackBug

Now:
solvedSearchBackBug

### CODE REVIEW

**Review by rob729 — CHANGES_REQUESTED** [review]
@shashwatjolly Squash your commits into a single commit.
Also, add a gif showing the result of the changes you made in the source code.

**Comment by ankushmundhra** [comment]
@shashwatjolly is this issue solved? if not i would love to work on it.

**Comment by iamareebjamal** [comment]
This is a PR

**Review by atm1504 — APPROVED** [review]

**Comment by shashwatjolly** [comment]
@atm1504 What do I need to do to fix the CircleCI build?

**Pull request merged**
