### PR TITLE
Fixes #177 : UI Issues with Timestamps

### LINKED ISSUE #177: UI issue with the timestamps
7f21071a-9165-11e6-8086-5320e30f7a9f

### PR DESCRIPTION
**Pull request by betterclever**
### Changes : 
1) Mid Width defined for message layouts
2) New TimeStamp Layout Applied to Map and LinkPreview views too.
### Screenshots for the change : 
screenshot_20161013-194457

### CODE REVIEW

**Comment by jig08** [comment]
@betterclever Follow the naming format , change the commit name too as `Fixes #177 : UI Issues with Timestamps`

**Comment by betterclever** [comment]
@jig08 Okay

**Comment by daminisatya** [comment]
@mariobehling please have a look at the screenshot.

**Comment by the-dagger** [comment]
@betterclever could you remove the margin above the input text box? 
There is a small margin of about 2-4dp which is cutting a part of the chat message. 
Please set the margin top for the input text box to 0dp.
It's not a big issue as such, but I think that the current ui looks a bit awkward.

**Comment by betterclever** [comment]
screenshot_20161014-093740

@the-dagger @daminisatya Is it fine now?

**Comment by betterclever** [comment]
@the-dagger @jig08 @daminisatya  Please restart Travis Build.

**Comment by daminisatya** [comment]
restarted

**Comment by jig08** [comment]
Yep, looks good enough.

**Pull request merged**
