### PR TITLE
chore: updated kotlin version from 1.3.21 to 1.3.30

### LINKED ISSUE #2168: Update kotlin version
**Describe the bug**
The kotlin version is currently not updated. 

**Expected Behaviour**
Update kotlin version from 1.3.21 to newer version 1.3.30

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by Bhavnaharitsa**
Fixes #2168 
Changes:  Updated kotlin version from 1.3.21 to 1.3.30 in build.gradle file

### CODE REVIEW

**Comment by Bhavnaharitsa** [comment]
Thanks for the title and @iamareebjamal could you please merge this !!

**Comment by iamareebjamal** [comment]
Circle CI is not running for some reason

**Comment by iamareebjamal** [comment]
@atm1504 Please fork and create a PR

**Comment by atm1504** [comment]
@iamareebjamal please close this.

**Pull request closed without merging**
