### PR TITLE
Fixed #1703 login option added in the overflow menu

### LINKED ISSUE #1703: Add signin / signup option in the menu
**Actual Behaviour**

User is not able to sign in / sign up later if he skips the sign in /sign up process when the app starts for the first time

**Expected Behaviour**

User must be able to sign in / sign up anytime he wants

**Steps to reproduce it**

Option for sign in / sign up can be added to  the menu  which will take the user to sign in page

**Would you like to work on the issue?**

Yes , I would like to work on this issue

### PR DESCRIPTION
**Pull request by Princejhabak**
Fixes #1703 

Changes: User can log in / sign up anytime he wants if he has skipped the process of log in / sign up. Option for login has been added to the overflow menu which will take the user to log in page.

Screenshots for the change: 

whatsapp image 2018-09-26 at 20 44 48

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Please follow commit guidelines

**Comment by Princejhabak** [comment]
@iamareebjamal, I've fixed the commit as per guidelines, please review my PR again.

**Comment by iamareebjamal** [comment]
Please follow this - https://chris.beams.io/posts/git-commit/

Thanks :)

**Comment by arundhati24** [comment]
@Princejhabak Please follow the commit guidelines as requested by @iamareebjamal and please squash the commits as well. :)

**Comment by Princejhabak** [comment]
@arundhati24   The overflow menu will not show login option if the user is already logged in.

**Comment by Princejhabak** [comment]
@iamareebjamal I apologize for closing this PR, I accidentally squashed wrong commits.

**Pull request closed without merging**
