### PR TITLE
fix ui issues with app 

### PR DESCRIPTION
**Pull request by amitiwary999**
Fixes issue #857
1. changing changing actionmode bar according to google assistant

### CODE REVIEW

**Comment by amitiwary999** [comment]
@mayank408 you can check [apk](https://drive.google.com/open?id=0B8gIkH5cqXi3eUVUOGhVdVdTek0) file. Currently I can't work on mainactivity so I will share another apk which include work on mainactivity and trying to solve issue #856 .

**Comment by amitiwary999** [comment]
screenshot_2017-07-28-13-37-59

screenshot_2017-07-28-13-37-46

screenshot_2017-07-28-13-32-32

screenshot_2017-07-28-13-06-56

screenshot_2017-07-28-13-03-00

screenshot_2017-07-28-13-02-35

**Comment by chiragw15** [comment]
@amitiwary999 The switch button is not looking nice IMO. Look at the screenshots here https://github.com/fossasia/susi_iOS/pull/181. Looks good to me. @chashmeetsingh What do you think?

**Comment by chashmeetsingh** [comment]
Ya, I guess the radio button before was looking much better.

**Comment by chiragw15** [comment]
Not required now. Themes are removed.

**Pull request closed without merging**
