### PR TITLE
refracting and skill listing

### LINKED ISSUE #897: Implement Skill Listing
Implement Skill Listing similar to Google Assistant and susi_skill cms 

screenshot from 2017-08-15 15 25 58

Use these APIs to get data for displaying.

http://api.susi.ai/cms/getSkillList.json?group=Entertainment
http://api.susi.ai/cms/getSkillList.json?group=Knowledge
etc

### PR DESCRIPTION
**Pull request by chiragw15**
Fixes #897 
Changes: 
Refracting and Skill listing.

.
.
Google Assistant displays skills like this.

.
.
skill cms displays skills like this
screenshot from 2017-08-15 15 25 58

.
.
Combined them to display skills like this

### CODE REVIEW

**Comment by mariobehling** [comment]
Screenshots?

**Comment by chiragw15** [comment]
@mariobehling @amitiwary999 @betterclever @chashmeetsingh @dynamitechetan @saurabhjn76 please review

**Comment by chashmeetsingh** [comment]
@chiragw15 instead of having the SUSI.AI logo here why not make the title say `SUSI.AI Skills` or maybe just `Skills`, seems like repetition IMO. Take a look at the codacy issue as well.
Rest looks good.

**Comment by betterclever** [comment]
@chiragw15, Chashmeet is right. SUSI AI written twice seems redundant.

**Comment by betterclever** [comment]
Rest looks good.

**Comment by chiragw15** [comment]
@betterclever @chashmeetsingh done. The codacy issue is arriving because there is a package name "skillListing" and codacy wants it to be changed to "skilllisting" (all lower case) which looks odd in my opinion. So, what should we do in that situation?

**Comment by chiragw15** [comment]
@chashmeetsingh @betterclever fixed codacy issue as well.

**Pull request merged**
