### PR TITLE
fix : Changed all Boolean to boolean 

### PR DESCRIPTION
**Pull request by chiragw15**
Fixes issue #658 

Changes: Changed Boolean to boolean

### CODE REVIEW

**Comment by iamareebjamal** [comment]
@chiragw15 Wouldn't it be better if all class types are changed to primitives in a single PR?

**Comment by chiragw15** [comment]
I did that only. These are the ones I found. Did I miss some of them?

**Comment by iamareebjamal** [comment]
I was talking about all class types, not just boolean, over the whole project

**Comment by chiragw15** [comment]
Alright, I thought you meant all Boolean over the project. Thanks. Will do the rest too.

**Comment by chiragw15** [comment]
@iamareebjamal Should the Class types in POJO class of retrofit responses be changed to primitive type too? Example [here](https://github.com/fossasia/susi_android/blob/development/app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Datum.java#L24)

**Comment by iamareebjamal** [comment]
Yes, they should be

**Comment by chiragw15** [comment]
@iamareebjamal done. Please review.

**Pull request merged**
