### PR TITLE
Feat: Report Skill feature added

### LINKED ISSUE #1530: Add feature to report a skill
**Actual Behaviour**

Currently, there is no option to allow the user to report a skill.

**Expected Behaviour**

Add this option in the skill details screen.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by codedsun**
Fixes #1530 : Added feature to report a skill

Changes: Added the api

Screenshots for the change:

### CODE REVIEW

**Comment by codedsun** [comment]
@iamareebjamal Chck this

**Comment by iamareebjamal** [comment]
@arundhati24 Why was this closed without explanation?

**Comment by codedsun** [comment]
@iamareebjamal Please chck the issue, all the explanation are there. Fix#1530

**Comment by arundhati24** [comment]
@codedsun Actually your branch has been force pushed or recreated, hence it can't be reopened. You have the code changes locally. Please push the changes again.

**Pull request closed without merging**
