### PR TITLE
chore: Update the readme file (https://github.com/fossasia/susi_android/issues/2364)

### PR DESCRIPTION
**Pull request by Zyro9922**
**Changes made**
- Added the screenshots provided in (https://github.com/fossasia/susi_android/issues/2364) in ./fastlane/metadata/android/en-US/images/phoneScreenshots
- Updated the screenshots section of readme accordingly with the new screenshots
- Under Roadmaps added a point about Susi Smart Speaker Configuration and Control
- Under Libraries used and their documentation section added the following: Play services authentication (Smart Lock for Passwords on Android) - https://developers.google.com/identity/smartlock-passwords/android/store-credentials

### CODE REVIEW

**Comment by atm1504** [comment]
@Zyro9922 there are few more changes that needs to be done in the readme file. I will give you all the other details today.

**Comment by atm1504** [comment]
@Zyro9922 
* Please update all the existing screenshots. 
* Merge the two sections (shown in photo) to one only.
Screenshot 2019-09-03 at 7 31 08 AM

If doubt still exists, feel free to ask.

**Comment by atm1504** [comment]
@Zyro9922 do merge the ```Code Practices``` and ```Join the development``` section into one section, as mentioned in the above section

**Comment by Zyro9922** [comment]
> @Zyro9922 do merge the `Code Practices` and `Join the development` section into one section, as mentioned in the above section

Done 👍

**Comment by Zyro9922** [comment]
Do I need to make any more changes?

**Comment by atm1504** [comment]
@Zyro9922 from next time create a different branch for each work you do. Never ever make commit directly from your development branch. Be careful. Follow the guidelines properly.

**Review by atm1504 — APPROVED** [review]

**Pull request merged**
