### PR TITLE
fixes issue #181 and #183: UI enhancements

### PR DESCRIPTION
**Pull request by aakashkhatter1296**
### Changes : 
Fixed hiding of login and signup buttons when keyboard opens in Login and SignUp screens. Added back button on SignUp screen.

### Screenshots for the change : 
fixed-login-screen
fixed-signup-screen

### CODE REVIEW

**Comment by jig08** [comment]
@aakashkhatter1296 Are you looking into the reasons for Travis failure ?

**Comment by aakashkhatter1296** [comment]
@jig08 yes, I am working on it.

**Comment by aakashkhatter1296** [comment]
@the-dagger Could you help me with the Travis failure ? I am unable to identify the errors.

**Comment by the-dagger** [comment]
@aakashkhatter1296 Could you resolve the conflicts?

**Comment by aakashkhatter1296** [comment]
@the-dagger Yes, working on it.

**Comment by the-dagger** [comment]
Please sync your fork and send the Pull Request again so that it can pass CircleCI tests.

**Pull request closed without merging**
