### PR TITLE
feat: Enhance the UI of the device card similar to google home

### LINKED ISSUE #2294: Enhance the UI of View Connected Device Page
**Describe the feature you'd like**
Enhance the UI of the viewConnectedDevice fragment. Try to establish a look similar to that present in google home.

**Additional context**
The issue is as per creating a standard method of a setup similar to google home, as discussed in the meeting.

**Screenshots**
GoogleHomeApp2017DevicesGoogleHomeMini_001

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by atm1504**
Fixes #2294 

Changes: 

Screenshots for the change: 
To be added
Screenshot 2019-07-02 at 8 35 20 PM

In google home:
GoogleHomeApp2017DevicesGoogleHomeMini_001

### CODE REVIEW

**Comment by atm1504** [comment]
@iamareebjamal @liveHarshit please review it.

**Comment by iamareebjamal** [comment]
The image used can be immensely improved

**Comment by atm1504** [comment]
> The image used can be immensely improved

@iamareebjamal u mean to I should change the image that I have used here. If so can you please suggest a better type of image. Or shall I download any non-copyright image and use here?

**Comment by iamareebjamal** [comment]
Last option

**Comment by atm1504** [comment]
Updated image (copyright issue not present): 
Screenshot 2019-07-04 at 3 59 25 PM

**Comment by atm1504** [comment]
@iamareebjamal please review it.

**Pull request merged**
