### PR TITLE
fix: migrating circleci build from version 1.0 to 2.0

### LINKED ISSUE #1964: Fix CircleCI build
Circle CI is not working. Change the config to 2.0

### PR DESCRIPTION
**Pull request by naman653**
Fixes #1964

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Do you really think migrating something from 1.0 to 2.0, a major upgrade will just work by changing the version number?

**Comment by iamareebjamal** [comment]
I wouldn't have created an issue if that was the case, I would have just changed the number myself

**Comment by naman653** [comment]
I know what you're saying but I need more info on what changes needs to be done.

**Comment by iamareebjamal** [comment]
I'm sorry then, this issue is not for you

**Comment by naman653** [comment]
My forked repo is building in circleci. Also circleci 1.0 will be discontinued after 15 March. The reason for not building in circleci is shown --> 
screenshot from 2019-02-17 21-38-43

**Comment by naman653** [comment]
Also we need to delete circle.yml file and make new file .circleci/config.yml according to docs which I had done in the PR.

**Comment by iamareebjamal** [comment]
You sent a PR to this project, meaning the changes you made in your repo are here as well, including the renaming of the file. So, that's not the issue

**Comment by iamareebjamal** [comment]
Seems they changed the requirement of following the project. Nevertheless, we need to change the config to 2.0

**Comment by naman653** [comment]
So it's not the issue of config.yml file.

**Pull request closed without merging**
