### PR TITLE
Add moshi converter for reducing boilerplate code

### PR DESCRIPTION
**Pull request by S2606**
Fixes https://github.com/fossasia/susi_android/issues/848

### CODE REVIEW

**Comment by S2606** [comment]
@chiragw15 As per the previous conversation does it mean to convert all the files in susi folder into one file??

**Comment by chiragw15** [comment]
Yes. rest->responses->susi contains all responses from Susi. Will be better if all the classes are written in a single file.

**Comment by chiragw15** [comment]
And same goes for location type responses and web search responses

**Comment by S2606** [comment]
location and responses are already done. Only susi is left to be done

**Comment by S2606** [comment]
@chiragw15 Please review

**Comment by chiragw15** [comment]
@S2606 please check why circle ci is not building

**Comment by chiragw15** [comment]
@S2606 The build is failing. Please check. There are unresolved references of some Classes and variables.

**Comment by S2606** [comment]
@chiragw15 Ok

**Comment by S2606** [comment]
@chiragw15 I would like to talk about this PR.
As per the issue, each and every file needs to be converted to Kotlin for moshi but the thing is some files cannot be converted as they are indeed crashing the app.
So what i would suggest is to keep the same serialized form so that the app remain stable.

Do give your reply.

**Comment by chiragw15** [comment]
@S2606 Ohh. Is there a specific reason that only some files are not converting. What is the major roadblock here? Is this a problem with moshi convertor? What alternative do we have? See, the main motive of the issue is to reduce the boiler plate code. If you have any other alternative which could reduce unnecessary 1000 lines to say 200 lines, that would be great. If not, it is still working fine currently.

**Comment by S2606** [comment]
@chiragw15 The problem isnt with moshi converter. The problem is since some files cant be converted, what is the use of keeping both moshi as well as gson converter?? if gson will stay then might as well not change at all??For me frankly speaking bring moshi coverter isnt feasible.

**Comment by chiragw15** [comment]
>the problem is since some files cant be converted

That's what I am asking. Why can't some files be converted?

>what is the use of keeping both moshi as well as gson converter?

No, we won't keep both. If moshi works fine, well and good else gson is doing it's job just fine.

>For me frankly speaking bring moshi coverter isnt feasible right now.

Any other option you have in mind. The main requirement is to reduce number of lines of unnecessary code.

**Comment by S2606** [comment]
That's what I am asking. Why can't some files be converted?
Expected top level declaration. An error i seriously unable to solve it and there is not much regarding this on the internet.This error particularly comes when converting datum.java file into kotlin

**Comment by chiragw15** [comment]
It's not necessary to convert all files to Kotlin. You can keep datum as it is and convert all other susi response files to one. Try this if it works.

**Comment by S2606** [comment]
@chiragw15 I am trying it until now but it isnt working.

**Comment by iamareebjamal** [comment]
Just adding to the discussion, GSON does not need `@SerializedName` if the property name matches the JSON field name

**Comment by chiragw15** [comment]
But Moshi has more advantages than that. Nevermind. @S2606  Could you just remove the `@SerializedName` wherever possible?

**Comment by S2606** [comment]
@chiragw15 Can i create a new PR??

**Comment by chiragw15** [comment]
@S2606 yes please.

**Pull request closed without merging**
