### PR TITLE
Fixes #520 : Adding feature to select server

### LINKED ISSUE #520: Add option to choose Susi AI server URL to settings
Currently a lot of development is going on. The outcome of the server changes cannot be easily tested and developers need to set up the complete stack to do this. Also, user possibly want to change their server in the future.

Therefore please implement an option in the setting to choose the Susi AI server. Offer the option to choose a) Susi AI standard server and b) Enter URL for other Server.

Please ensure, the calls of the API are abstracted and use the URL specified in the settings.

### PR DESCRIPTION
**Pull request by chiragw15**
Fixes issue #520 

Changes:Added a feature in which user can either select susi default server or a his own server.

EDIT : Changed the unit test accordingly.

Screenshots for the change: 

screenshot_20170303-224607

### CODE REVIEW

**Comment by chiragw15** [comment]
@the-dagger if you are free, can you have a look at it?

**Comment by Abhi2424shek** [comment]
@chiragw15 please check the failing tests.

**Comment by chiragw15** [comment]
@Abhi2424shek only the codacy test is failing. It is because of using butterknife. It always gives this error "Use explicit scoping instead of the default package private level" when we write something like @BindView(R.id.something)

**Comment by Abhi2424shek** [comment]
Yea there's a workaround I guess...

**Comment by chiragw15** [comment]
@Abhi2424shek done. All checks passed.

**Pull request merged**
