### PR TITLE
Fixes #1051

### LINKED ISSUE #1051: Implement chat bubble when app goes in background.
When the app goes in background. chat bubble like facebook messenger pop's up.

**Would you like to work on the issue?**

Yes i am working on this.

### PR DESCRIPTION
**Pull request by yashLadha**
Floating Widget Popup

Fixes #1051 

Changes:Implement a floating widget service that comes up when app goes in background and stops when app is removed.

### CODE REVIEW

**Comment by yashLadha** [comment]
When the app goes in background pop up appears and when its instance gets removed the service stops. I need help in the part for the querying part, because this is not related to the app. It's an instant popup for querying and should not include the previous chat history. May be later in future we can add the permission for showing the previous chat history in the floating widget. 
Another thing that There is a need for other Adapter class for the floating widget, should i make it as a separate adapter and do not use the present `ChatFeedAdapter`. Views @chiragw15 @collinx @codedsun

**Comment by yashLadha** [comment]
I am waiting for the views of @chiragw15 @collinx on this PR and issue if you read it. @0x48piraj There is more work to do in this PR. It's a dummy PR as of know.

**Comment by chiragw15** [comment]
@yashLadha Can you please provide an apk for testing.

**Comment by yashLadha** [comment]
It haven't completed yet. Unable to work on that, due to time constraint.

**Comment by chiragw15** [comment]
Okay. The PR is open then. Please push the commits in this PR only. Let me know when complete.

**Comment by aniket-agarwal1999** [comment]
Hello @chiragw15 can I please claim this issue as it has been stagnant for some time now.

**Comment by yashLadha** [comment]
I have been busy with my in semester exams will sent a pr in a day or two.
Thank you.

**Comment by aniket-agarwal1999** [comment]
@yashLadha Okay :)

**Comment by yashLadha** [comment]
Yes you can continue the work on top of mine @batbrain7  :+1: cheers

**Comment by batbrain7** [comment]
@iamareebjamal can I send a new PR for this?

**Comment by iamareebjamal** [comment]
Yes, but in some time as there are other important issue. I will close this PR then

**Pull request closed without merging**
