### PR TITLE
fix: skill variable initialized #1855

### LINKED ISSUE #1855: skill variable not initialized
**Describe the bug**
skills variable is only declared but is not assigned any value in SkillsActivity.kt & SkillListingFragment.kt

**Expected Behaviour**
skills variable should be initialized from database

**Steps To Reproduce it**
Try to print the size of skill variable. You will find it to be zero.

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by Nimagna123**
Fixes #1855 
Changes: Initialized the skills variable in SkillsActivity.kt , SkillListingFragment.kt , SkillListingPresenter.kt

### CODE REVIEW

**Comment by Nimagna123** [comment]
What are the pr guidelines that i have not followed? I am new in thiss project.

**Comment by Nimagna123** [comment]
What PR Guidelines has not been followed?

**Comment by iamareebjamal** [comment]
You are not following PR template

**Comment by Nimagna123** [comment]
I am made necessary changes in commitment style ( Comment ).
Is this enough.

**Comment by iamareebjamal** [comment]
Your build is failing https://circleci.com/gh/fossasia/susi_android/4328?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Pull request merged**
