### PR TITLE
Fix #1137-Added splash screen for the app.

### LINKED ISSUE #1137: Add splash screen.
**Actual Behaviour**

On launching the application, the login page appears or the user is directed to the chat interface if he/she is logged in.

**Expected Behaviour**

A splash screen can be added which would be displayed for a very short period of time before the user is directed to the login page or the chat interface.

**Steps to reproduce it**

Launch the app.

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by sauravvishal8797**
Fixes #1137 

Changes: Added an Activity for the splashscreen view, modified the manifest files.

GIF displaying the change:
videotogif_2018 03 01_22 26 09

### CODE REVIEW

**Comment by sauravvishal8797** [comment]
@chiragw15 Please review.

**Comment by arundhati24** [comment]
@sauravvishal8797  Could you please add the screenshots for the change? :smiley:

**Comment by sauravvishal8797** [comment]
@arundhati24  Added the GIF displaying the change, please have a look.:smile:

**Comment by ujjwalagr** [comment]
@sauravvishal8797 You can add the logo of susi ai that is launcher icon of the project in your splash screen it will look more beautiful and something "proffesional". I added that when I solved it and believe me it was looking too good

**Comment by chiragw15** [comment]
closing wrt https://github.com/fossasia/susi_android/issues/385

**Comment by harshitbansal05** [comment]
@sauravvishal8797 this is not the correct way of implementing splash screen. You can refer this: https://medium.com/@ssaurel/create-a-splash-screen-on-android-the-right-way-93d6fb444857. @chiragw15 I think the problem was with the wrong implementation of splash screen. Most google apps do have a splash screen to replace the white screen on app startup with the brandable logo of the app.
https://material.io/guidelines/patterns/launch-screens.html#launch-screens-branded-launch.

**Pull request closed without merging**
