### PR TITLE
Fixes #67: Added timeStamp to messages

### LINKED ISSUE #67: Add timestamp on chat message

### PR DESCRIPTION
**Pull request by code-crusher**
> Note: Before running the app clear the data, as realm model is modified :)

Here is a screenshot:
device-2016-10-05-075830

### CODE REVIEW

**Comment by daminisatya** [comment]
@code-crusher please squash your commits and should look like the description!

**Comment by daminisatya** [comment]
+1 code looks clean

**Comment by daminisatya** [comment]
@code-crusher Your commit message should be like this ```Fixes #67: Added timeStamp to messages```

**Comment by mariobehling** [comment]
@code-crusher Thank you. Please resolve merge conflicts. Cheers.

**Comment by daminisatya** [comment]
@code-crusher Redundancy. Squash please
redundancy

**Comment by code-crusher** [comment]
@daminisatya While squashing i'm getting merge confilts.

**Comment by daminisatya** [comment]
@code-crusher did you pull the latest updates?

**Comment by code-crusher** [comment]
@daminisatya Yes i did. Can i do a new PR? This is taking a lot time 😅

**Comment by daminisatya** [comment]
@code-crusher Sure. :D

**Comment by jig08** [comment]
@code-crusher Closing this PR then.

**Pull request closed without merging**
