### PR TITLE
chore: refactor rateskill code in viewholders

### LINKED ISSUE #2269: refactor the code in viewholders
**Describe the chore**

There is duplicate code present in viewholders for sending the request to rate the skill and likewise updating the thumbs up and thumbs down button.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by batbrain7**
Fixes #2269 

Changes: Added the API call at only one place which is the MessageViewHolder which is extended by other viewholders

### CODE REVIEW

**Comment by atm1504** [comment]
@batbrain7 the circle ci probably failed because of heavy load in the circleci server. Just retrigger it. It will be able to build.

**Comment by batbrain7** [comment]
@iamareebjamal I am able to successfully run the tests locally, could you please assert is triggering the CI will help ?

**Comment by liveHarshit** [comment]
> Just retrigger it. It will be able to build.

I don't think so, IMO need to do changes in unit test files.

**Comment by atm1504** [comment]
> > Just retrigger it. It will be able to build.
> 
> I don't think so, IMO need to do changes in unit test files.

Probably u r right. But, I faced this issue earlier and retriggering it did work out. If error lies in the unit test file, I think we should make an issue to solve it. : )

**Comment by atm1504** [comment]
> @iamareebjamal I am able to successfully run the tests locally, could you please assert is triggering the CI will help ?

@batbrain7 just add or delete an unnecessary line and push it. It will automatically trigger the build. : )

**Comment by liveHarshit** [comment]
> @batbrain7 just add or delete an unnecessary line and push it. It will automatically trigger the build. : )

Oh, what a great idea... :sweat_smile:

**Comment by batbrain7** [comment]
all checks have been passed

**Pull request merged**
