### PR TITLE
refactor: Fully migrate to Kotlin

### PR DESCRIPTION
**Pull request by iamareebjamal**
Fully migrate the codebase to Kotlin

There are some things remaining:

- [ ] model nullability
- [ ] Base URL change

### CODE REVIEW

**Comment by iamareebjamal** [comment]
copy SkillRatingQuery with polarity

**Comment by iamareebjamal** [comment]
Model positively and negatively rated

**Comment by iamareebjamal** [comment]
Major ViewHolders contain same code. Eliminate duplication

**Comment by iamareebjamal** [comment]
@arundhati24 @batbrain7 Take a look at ImageViewHolder for example. Shouldn't all code be inside 

```
if (model != null) {
 ...
}
```

Why do we have code outside it? Is there any case where model can be null? And if there is, then it will throw an exception because it is outside the check. Please check and let me know ASAP

**Comment by iamareebjamal** [comment]
@arundhati24 @batbrain7 We need to get this branch tested thoroughly in order to move ahead with the completion of migration

**Comment by batbrain7** [comment]
@iamareebjamal okay testing this branch

**Comment by iamareebjamal** [comment]
@batbrain7 @arundhati24 Is this branch tested? We need to merge this

**Comment by iamareebjamal** [comment]
Merging after resolving conflicts. If there are some bugs, they'll be solved in future

**Pull request merged**
