### PR TITLE
added back feature from sign up activity to skillsActivity

### LINKED ISSUE #2136: Login page from menu bar closes the app after pressing back
**Describe the bug**
If the user hasn't logged in, he clicks the login page under menu in SkillsActivity and it directs to the login page . But for some reasons if he doesn't want to login and clicks back button,the app closes down. 

**Expected Behaviour**
On clicking back button, it should go back to menu bar in SkillsAcitivity so that s/he can continue using the app.
The same can be implemented for signup page as well.

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by Bhavnaharitsa**
Fixes #2136 
Changes: an extension to that issue .
Sorry I had to close that pull request as unwanted commits were getting added.

### CODE REVIEW

**Comment by Bhavnaharitsa** [comment]
@iamareebjamal @batbrain7 Please review sir !

**Comment by Bhavnaharitsa** [comment]
@iamareebjamal Do you know how to cherry pick commits using commit id in AS ?
Please help on that!

**Comment by Bhavnaharitsa** [comment]
> Also, I feel this is not an enhancement that is needed at the moment. Please check out other open issues. There are so many features and bugs to work upon.

Thanks for the link. Already working on some, shall definitely work on other important issues too.

**Comment by arundhati24** [comment]
@Bhavnaharitsa Great, do go through existing issues to check if you can work on some of the features rather than making small enhancements. Please understand that we have many features that are yet to be completed and that is a priority. For now, I need to close this PR as this is not needed at the moment. :)

**Pull request closed without merging**
