### PR TITLE
Fix : app crashes after logout

### PR DESCRIPTION
**Pull request by amitiwary999**
Fixes issue #742 

Screenshots for the change:

### CODE REVIEW

**Comment by amitiwary999** [comment]
@mayank408 I explained reason [here](https://github.com/fossasia/susi_android/issues/742). Here I am checking if user is logout(after logout token expire and realm closed) then not perform linkpreview work(background work).

**Comment by chiragw15** [comment]
@amitiwary999 You said in #742 that
>Reason for crash is after logout realm closed but linkpreview still running in background and it try to change real object but realm is already closed.

If this is the case, shouldn't the app crash too when app is closed because realm instance is closed in onDestroy mehtod. ([here](https://github.com/fossasia/susi_android/blob/development/app/src/main/java/org/fossasia/susi/ai/activities/MainActivity.java#L1605))

**Comment by chiragw15** [comment]
@the-dagger I have a doubt. Is linkPreviewCallback ([here](https://github.com/fossasia/susi_android/blob/development/app/src/main/java/org/fossasia/susi/ai/adapters/recycleradapters/ChatFeedRecyclerAdapter.java#L620)) executed after main activity is closed. Or in general are call backs executed if the app is closed or the activity is destroyed?

**Comment by amitiwary999** [comment]
@chiragw15 in onDestroy we are not deleting realm. But in case of logout we are deleting realm objects. I think that's why app is not crashing. In logcat it is shown that ' Object is no longer valid to operate on.Was it deleted by another thread?'

**Pull request merged**
