### PR TITLE
fix: Use suitable layout on orientation change

### LINKED ISSUE #1925: Layout does not change on orientation change
**Describe the bug**
SkillDetails Fragmant has different layout files for portrait and landscape mode.
But on screen rotation same layout is shown.

**Expected Behaviour**
Layout should change on rotation

**Steps to reproduce it**
1. Open SkillDetailsFragment
2. Rotate Mobile

**Screenshots of the issue**

whatsappvideo20190210at64 1

whatsappvideo20190210at64

**Smartphone Info:**

|               | |
|---------------|-|
|Device         | [ Moto G4 Plus] |
|Android Version|[ Nougat 7.0]  |

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by ravi-kishan**
Fixes #1925 Layout change does not change on orientation change
Changes: 
Detached and attached the fragment

Screenshots for the change: 
whatsappvideo20190210at11 2

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Why is this needed in the first place?

**Comment by ravi-kishan** [comment]
There are different layout files for portrait and landscape mode but the layout does not change on rotation.

**Comment by iamareebjamal** [comment]
Why?

**Comment by ravi-kishan** [comment]
In the manifest it is mentioned that configuration changes will be handled programmatically. So we need to overwrite this function.

**Comment by iamareebjamal** [comment]
Change the manifest

**Comment by ravi-kishan** [comment]
Sorry the manifest code which I was referring is for the parent activity of this fragment.
Changing that code has no effect on this fragment behavior.

Detaching and attaching the fragment renews its layout as per the orientation of phone.

**Comment by iamareebjamal** [comment]
This code should not be needed

**Comment by atm1504** [comment]
@arundhati24 @batbrain7 this pr has been opened for a long time, and as areeb sir stated, it is not required, so I think this should be closed.

**Pull request closed without merging**
