### PR TITLE
adressed #62: linkified all links sent by susi.

### LINKED ISSUE #62: Linkify Links
Currently some answers generate links, but these are not clickable.

### PR DESCRIPTION
**Pull request by gogeta95**
* Changed colors, same as web client.
* Optimised layouts.

fixes #62.

ScreenShot: 
image

### CODE REVIEW

**Comment by daminisatya** [comment]
Awesome! But the Susi AI bar is not in sync with the chat bubble colors. Why dont you have a look at susi webclient and use the light blue shade?

**Comment by gogeta95** [comment]
how about action bar same color as send button?

**Comment by daminisatya** [comment]
Looks great. I would vote for the second screenshot

**Comment by gogeta95** [comment]
@the-dagger which one should we approve?

**Comment by the-dagger** [comment]
@gogeta95 I vote for the second one. 
Also change the color of send button to match the action bar.

**Comment by gogeta95** [comment]
Updated the PR and changed colors, final UI is below.
image

**Comment by daminisatya** [comment]
@gogeta95 Help us follow the best practice. Always remember to map your commit to the corresponding issue. That means one proper commit per issue. Which helps us to go through the code in order to check for bug regressions. Thank you!

**Comment by gogeta95** [comment]
I'd do that but @the-dagger said he always squashes while merging, so it's not an issue.

**Comment by sudheesh001** [comment]
@the-dagger Why is there the squash and merge approach. That's not the path we'd need to maintain the projects in the long run. Please follow these approaches strictly.
- Single commit per pull request
- Reference the issue numbers in the commit message.
- Direct merge and *NOT* merge with squash. In case there are multiple commits on the PR, the commit author needs to squash them and not the maintainers cherrypicking and merging squashes.

@gogeta95 please reference the issue numbers in the commit message. This is the standard practice.

@mariobehling Could you please ensure that these are the same steps followed across please.

**Comment by the-dagger** [comment]
@sudheesh001 I didn't know about this because in opev, we never merged a pull request directly instead we always squashed it ( because in case of a direct merge, there was an extra commit by the maintainer for a pull reuqest). 
But I'll keep this in mind from now on. 
I think that we should put this point up in the contribution docs as well

**Comment by daminisatya** [comment]
@the-dagger yes, it's good to put it in the docs.

**Comment by sudheesh001** [comment]
That's the same approach we use at coala but not here at loklak's projects. We ensure that the merge commit is there because it's easier that way to find the merges where the code was last stable in case of a bad checkin into the master. That way the person who reviewed it is accountable for ensuring quality. The merge not showing up is a process that can be used if the PR before the commit and the master have the same head i.e. always rebase and squash before merge and squash. A good tool for that is Rultor http://rultor.com/ but lets not change how we merge and review patches here and please follow the guidelines mentioned and add them to the repository.

**Pull request merged**
