### PR TITLE
Fix #656: Remove html escape sequences from responses

### LINKED ISSUE #656: Correctly format HTML escape characters from response
**Actual Behaviour**

Currently, the response shows HTML escaped characters as is without formatting them to normal text

**Expected Behaviour**

Correct formatting must be done before showing the results.

**Steps to reproduce it**

Run any query with return response containing escape characters

**Screenshots of the issue**

device-2017-06-03-220117

**Would you like to work on the issue?**

No

### PR DESCRIPTION
**Pull request by Muks14x**
Fixes issue #656 

Changes: Add a html escape sequence filter before adding message to the database.

### CODE REVIEW

**Comment by chiragw15** [comment]
@Muks14x Can you change commit message according to guidelines. Thanks. https://github.com/fossasia/susi_android/blob/development/docs/commitStyle.md

**Comment by Muks14x** [comment]
@chiragw15 Is the commit message more compliant to guidelines now, or am I overlooking something?

**Comment by iamareebjamal** [comment]
Don't add the issue number in commit message itself. Adding it in the description is sufficient

**Comment by chiragw15** [comment]
@Muks14x don't add issue number in it. Keep it like "fix: Add filter for html escape sequences"

**Comment by Muks14x** [comment]
@chiragw15 @iamareebjamal Sorry, I've added the issue number to the Footer like the style guide specifies now.

**Pull request merged**
