### PR TITLE
Issue #48 Fixed

### PR DESCRIPTION
**Pull request by sagarchoudhary96**
Message Sending on Pressing Enter Key

### CODE REVIEW

**Comment by daminisatya** [comment]
Please give a meaningful commit message. Also squash the commits. I'm unable to review it cause your commit message is blank. Help us follow the best practice

**Comment by amitiwary999** [comment]
It is not working on my phone.

**Comment by gogeta95** [comment]
Hey, are we not doing as in WhatsApp I suggested?

**Comment by sagarchoudhary96** [comment]
@amitiwary999 which phone you are using?

**Comment by amitiwary999** [comment]
@sagarchoudhary96 Lenovo A6000 Plus

**Comment by gogeta95** [comment]
yes, not working @sagarchoudhary96 you tested it on emulator with hardware enter key i guess, where it is working. did you test with android soft keyboard?

**Comment by sagarchoudhary96** [comment]
@gogeta95 i tested it on my mobile phone not on emulator .. i will See To it ...

**Comment by sagarchoudhary96** [comment]
@gogeta95 @amitiwary999 @the-dagger   I have fixed the enter key issue, it's now working on android soft keyboard and all devices.

**Comment by amitiwary999** [comment]
If it is not working on android phone then what is its use

**Comment by sagarchoudhary96** [comment]
@amitiwary999 it's working on android phone ..i have commited it right now

**Comment by amitiwary999** [comment]
My mistake I have not see it...but it is not supporting multiline message ( like whatsapp )

**Comment by gogeta95** [comment]
It's correct now, multi line text can exist without pressing enter key.

**Comment by sagarchoudhary96** [comment]
@gogeta95  so now i add it in settings for user to select whether they want to use enter as send or not ryt ?

**Comment by gogeta95** [comment]
Yes, you can do it, but update the description as soon as it's done. So
everyone will know.

**Comment by sagarchoudhary96** [comment]
okay

**Comment by addiittya2006** [comment]
Add an option using the Preference Options Menu. Update PR and Issue Description.

Please Squash your commits with a Meaningful Commit Message.

**Comment by amitiwary999** [comment]
First update your repository then try to send pull request.

**Comment by sagarchoudhary96** [comment]
I Have made all the Changes as Required and Added Enter Key as Send as a Feature too...

**Pull request closed without merging**
