### PR TITLE
Full screen speech input implemented

### LINKED ISSUE #856: Make Speech input full Screen
Follow Siri and Cortana and implement a full-screen Speech input feature.

### PR DESCRIPTION
**Pull request by amitiwary999**
Fixes #856
included license.

### CODE REVIEW

**Comment by amitiwary999** [comment]
@chiragw15 I tried library again but using speech input continuously, it is not working properly. So I included the license.

**Comment by chiragw15** [comment]
>speech input continuously, it is not working properly

What problem did you face exactly?

**Comment by amitiwary999** [comment]
After giving speech input app not shows chat screen but gives voice reply. I implemented it fully using library [here](https://github.com/amitiwary999/susi_android/tree/speechcheck) and tested. Not always but sometimes it occurs.

**Comment by chiragw15** [comment]
>After giving speech input app not shows chat screen

Does not seem to be an issue with library. Strange. Let me try this once. Will let you know if I face same problem.

**Comment by amitiwary999** [comment]
Okay. I implemented it using library and link is given in above comment.

**Comment by chiragw15** [comment]
@amitiwary999 I pulled your code and tested. I guess there is a problem with library. So, it is fine for now if you have included license.

**Pull request merged**
