### PR TITLE
fixes issue #147 add an option in setting to disable STT

### PR DESCRIPTION
**Pull request by amitiwary999**
fixes issue #147 add an option in setting to disable STT

### CODE REVIEW

**Comment by amitiwary999** [comment]
@the-dagger I made the required changes but it again failed.

**Comment by amitiwary999** [comment]
@the-dagger Can you please review this?I made the required changes but it again failed.

**Comment by the-dagger** [comment]
OK, I will have a look.

**Comment by the-dagger** [comment]
@amitiwary999 Could you resolve the conflicts?

**Comment by amitiwary999** [comment]
Yes. working on it

**Pull request closed without merging**
