### PR TITLE
Fix : remove delete option from app[work in progress]

### PR DESCRIPTION
**Pull request by amitiwary999**
Fixes issue #755 

Changes:

### CODE REVIEW

**Comment by amitiwary999** [comment]
I am working on it. I forgot to write work in progress.

**Comment by mayank408** [comment]
@amitiwary999 Pls solve your previous issues first. It does not make any sense that you assign every issue to yourself and then write "work in progress". Also this issue was related to my yesterday Pr therefore let me solve this. You pls resolve your previous PRs until assigning yourself a new one.
@chiragw15 @amitiwary999 I am gonna work on this.

**Comment by chiragw15** [comment]
@amitiwary999 your PR #696 and #750 already have a label "Work in progress" on it. It's your third PR with this label. Does not make sense. Focus on one PR at a time. Only pick issues if you have completed your previous ones.

**Comment by amitiwary999** [comment]
@chiragw15 I mentioned that in pr [696](https://github.com/fossasia/susi_android/pull/696) moving clicklisttener is creating problem. @mayank408 I opened this issue yesterday and waited for your reply. But didn't get any response that's why I started working on it.

**Comment by mayank408** [comment]
@amitiwary999 At what time you were waiting for my reply. **"3 am" in the morning**.  does this make any sense.

**Comment by amitiwary999** [comment]
I have no problem if you want to work on this that's why initially I mentioned that I opened an issue you can work. I commented 3 hours ago I work on this issue. you can reply in morning.

**Comment by mayank408** [comment]
@amitiwary999 The thing is every one works at his or her own time frame, even when I saw the issue I was gonna comment on it but then I saw you already sent a PR. You should atleast wait for my reply. Pls work cooperatively.

**Comment by chiragw15** [comment]
@amitiwary leave this PR for now. Let's finish the old ones first. #696 you mentioned
>I have moved required code but there is a problem in removing clicklistener. I have tried to move clicklistener but facing some problem. I will try to fix it.

Question : Are you trying to fix it or do you need help?

**Comment by amitiwary999** [comment]
I tried to fix it and I moved clicklistener part to respective viewholder but it is not working properly. Yes I need some help.

**Comment by chiragw15** [comment]
Okay, will pull your code and try to fix it. Meanwhile complete #750.

**Pull request closed without merging**
