### PR TITLE
fix : compiled all build gradle dependency fields in config.gradle

### LINKED ISSUE #1032: Compiling all gradle fields' values in a single gradle file
**Actual Behaviour**

The code readability and code quality of the dependency fields in build gradle is not present.

**Expected Behaviour**

The build gradle should maintain the code readability and code quality. The constant fields should be present in another gradle file.

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by rishz**
Fixes #1032 

Changes:
Compiled all the dependencies version and constant fields in a separate file (config.gradle) for better code readability and quality

Screenshots for the change: 
screen shot 2017-10-21 at 7 29 05 pm

### CODE REVIEW

**Comment by rishz** [comment]
@chiragw15 @iamareebjamal Please review this PR.

**Comment by chiragw15** [comment]
@rishz the circle CI build is failing. Can you please check it.

**Comment by rishz** [comment]
@chiragw15 I'm unable to find out the reason. I just took a pull from upstream and resolved conflicts. Could you help?

**Comment by hardik124** [comment]
@rishz can u try squashing the commits?

**Pull request merged**
