### PR TITLE
chore: Release v1.3.0

### LINKED ISSUE #2320: Make new release of the app
**Describe the chore**
Make a new release of the app.

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by atm1504**
Fixes #2320 

Changes:
* A new method of setting up smart speaker has been implemented
* Bugs related to tts engine, visibility, app crash has been fixed
* Device section has been added

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Always bump version code and name

**Comment by atm1504** [comment]
> Always bump version code and name

I need to update the version number also in the gradle file also 
I am making a pr for that in about a minute

**Comment by iamareebjamal** [comment]
> also in the gradle file also

That is what I was talking about

**Comment by atm1504** [comment]
> > also in the gradle file also
> 
> That is what I was talking about

I am updating that now only.

**Pull request merged**
