### PR TITLE
chore: updated version code and name

### PR DESCRIPTION
**Pull request by batbrain7**
Changes: Update for the new version on the playstore

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Fix YouTube playback first

**Comment by batbrain7** [comment]
@iamareebjamal on setting the API key YouTube playback works.

**Comment by iamareebjamal** [comment]
Set the environment variable without quotes and fix it. Currently, I have added workaround

**Comment by batbrain7** [comment]
@iamareebjamal the youtube play works on the apk branch apks

**Comment by batbrain7** [comment]
@iamareebjamal please merge this PR as a fixed version is required on play store asap as the crashed version is still present there, further issues could be rectified in the next PR.

**Pull request merged**
